Corrected and finished the debug option for the unified unattended installer
wazuh/wazuh-packages pull request #1042
Opened 2021-12-01 12:24 UTC by verdx

|Related issue|
|---|
| #974, #839|

## Description

## Logs example

## Tests

- Build the package in any supported platform
  - [ ] Linux
  - [ ] Windows
  - [ ] macOS
  - [ ] Solaris
  - [ ] AIX
  - [ ] HP-UX
- [ ] Package installation
- [ ] Package upgrade
- [ ] Package downgrade
- [ ] Package remove
- [ ] Package install/remove/install
- [ ] Change added to CHANGELOG.md

- Tests for Linux RPM
  - [ ] Build the package for x86_64
  - [ ] Build the package for i386
  - [ ] Build the package for armhf
  - [ ] Build the package for aarch64
  - [ ] `%files` section is correctly updated if necessary
- Tests for Linux deb
  - [ ] Build the package for x86_64
  - [ ] Build the package for i386
  - [ ] Build the package for armhf
  - [ ] Build the package for aarch64
  - [ ] Package install/remove/install
  - [ ] Package install/purge/install
  - [ ] Check file permissions after installing the package
- Tests for macOS
  - [ ] Test the package from macOS Sierra to Mojave
- Tests for Solaris
  - [ ] Test the package on Solaris 10
  - [ ] Test the package on Solaris 11
  - [ ] Check file permissions on Solaris 11 template
- Tests for IBM AIX
  - [ ] `%files` section is correctly updated if necessary
  - [ ] Check the changes from IBM AIX 5 to 7

2021-12-07 14:21 UTC, lastranikos reviewed
Is it necessary to have multiple logger functions?
and with different logfiles?

logger() {
logger_cert() {
logger_pass() {

2021-12-07 15:52 UTC, lastranikos commented on unattended_scripts/install_functions/opendistro/wazuh-cert-tool.sh
> +    logfile="/var/log/wazuh-cert-tool.log"
cool, LGTM

2021-12-07 15:52 UTC, lastranikos approved these changes
LGTM

2021-12-07 18:01 UTC, rauldpm requested changes
Good job, jsut a minor change. Review calls to echo, it must use logger

https://github.com/wazuh/wazuh-packages/blob/3af38121086e8f1d9e063762d31e6248e4f64945/unattended_scripts/install_functions/opendistro/elasticsearch.sh#L14

2021-12-09 15:23 UTC, verdx commented
> Good job, just a minor change. Review calls to echo, it must use logger
> 
> https://github.com/wazuh/wazuh-packages/blob/3af38121086e8f1d9e063762d31e6248e4f64945/unattended_scripts/install_functions/opendistro/elasticsearch.sh#L14

Changed in f97aeaa032877edde2aba5b649934742b24033a7

2021-12-09 15:26 UTC, rauldpm approved these changes
LGTM

2021-12-14 16:30 UTC, merged