Unify config.yml standard
wazuh/wazuh-packages pull request #1088
Opened 2021-12-17 17:47 UTC by DFolchA

|Related issue|
|---|
|#1045|

## Description

This PR changes the way the installer script reads the yaml files and sets a new standard for the config.yml file.

## Logs example

## Tests

- Build the package in any supported platform
  - [ ] Linux
  - [ ] Windows
  - [ ] macOS
  - [ ] Solaris
  - [ ] AIX
  - [ ] HP-UX
- [ ] Package installation
- [ ] Package upgrade
- [ ] Package downgrade
- [ ] Package remove
- [ ] Package install/remove/install
- [ ] Change added to CHANGELOG.md

- Tests for Linux RPM
  - [ ] Build the package for x86_64
  - [ ] Build the package for i386
  - [ ] Build the package for armhf
  - [ ] Build the package for aarch64
  - [ ] `%files` section is correctly updated if necessary
- Tests for Linux deb
  - [ ] Build the package for x86_64
  - [ ] Build the package for i386
  - [ ] Build the package for armhf
  - [ ] Build the package for aarch64
  - [ ] Package install/remove/install
  - [ ] Package install/purge/install
  - [ ] Check file permissions after installing the package
- Tests for macOS
  - [ ] Test the package from macOS Sierra to Mojave
- Tests for Solaris
  - [ ] Test the package on Solaris 10
  - [ ] Test the package on Solaris 11
  - [ ] Check file permissions on Solaris 11 template
- Tests for IBM AIX
  - [ ] `%files` section is correctly updated if necessary
  - [ ] Check the changes from IBM AIX 5 to 7

2021-12-17 18:18 UTC, verdx requested changes
GJ, only some minor changes

2021-12-17 18:18 UTC, verdx commented on unattended_scripts/config.yml
> +    # name: <elasticsearch-node-name>
Why are the name and ip commented?

2021-12-17 18:18 UTC, verdx commented on unattended_scripts/install_functions/opendistro/elasticsearch.sh
>      checkNodes
If you do not use the single anymore, this line should be erased

2021-12-17 18:18 UTC, verdx commented on unattended_scripts/install_functions/opendistro/wazuh-cert-tool.sh
> +# set -x
This shouldn't stay here.

2021-12-20 12:30 UTC, verdx approved these changes
LGTM

2021-12-23 12:39 UTC, alberpilot approved these changes
LGTM

2021-12-23 12:40 UTC, merged