Indexer v1 package SPECs
wazuh/wazuh-packages pull request #1226
Opened 2022-02-01 11:32 UTC by okynos

|Related issue|
|---|
| #1099 |

## Description

Hello team,

We want to merge this branch into big-product branch
We have included:
- Indexer Debian build scripts
- Indexer RPM build scripts
- Debian 4.3.0 indexer SPECs
- RPM 4.3.0 indexer SPECs
- Improved file permissions on both systems.
- Improved installation procedure.
- Added default roles and users to indexer package from unattended development.
- Added wazuh-cert-tool and wazuh-passwords-tool
- A lot more...

## Tests

- Build the package in any supported platform
  - [x] Linux
- [x] Package installation
- [x] Package remove

- Tests for Linux RPM
  - [x] Build the package for x86_64
  - [x] `%files` section is correctly updated if necessary
- Tests for Linux deb
  - [x] Build the package for x86_64
  - [x] Check file permissions after installing the package

2022-02-01 11:35 UTC, verdx approved these changes
LGTM

2022-02-02 21:00 UTC, alberpilot requested changes
- Change the certificate names and configuration files to `demo` name, as Opendistro. 
- The config.yml by default must include (commented) 3 elasticsearch nodes in total. The node names must be `node-1`, `node-2` and `node-3`. Like this:
```
nodes:
  # Elasticsearch server nodes
  elasticsearch:
    name: node-1
    ip: <elasticsearch-node-ip>
    # name: <elasticsearch-node-name>
    # ip: <elasticsearch-node-ip>
    # name: <elasticsearch-node-name>
    # ip: <elasticsearch-node-ip>

  # Wazuh server nodes
  # Use node_type only with more than one Wazuh manager
  wazuh_servers:
    name: wazuh-server
    ip: <wazuh-manager-ip>
    # node_type: master
    # name: <wazuh-node-name>
    # ip: <wazuh-manager-ip>
    # node_type: worker

  # Kibana node
  kibana:
    name: wazuh-dashboard
    ip: <kibana-node-ip>
```

2022-02-03 08:24 UTC, okynos commented on indexer/rpm/wazuh-indexer.spec
> +# Copyright (C) 2015-2022, Wazuh Inc.
v2

2022-02-03 08:25 UTC, okynos commented on indexer/rpm/wazuh-indexer.spec
> +# Wazuh package SPEC
2ad2a4d3

2022-02-03 08:26 UTC, okynos commented on stack/indexer/deb/debian/postinst
> +  # Setting Owner and group of own folders
5950942f

2022-02-03 08:27 UTC, okynos commented on stack/indexer/deb/debian/postinst
> +# Below codeblock is using the fact that postinst script is called with the most-recently configured version.
ea35c66c

2022-02-03 08:28 UTC, okynos commented on indexer/rpm/wazuh-indexer.spec
> +    fi
e7e9888c

2022-02-03 08:30 UTC, okynos commented on indexer/rpm/wazuh-indexer.spec
> +    fi
Nothing to do https://github.com/opensearch-project/OpenSearch/blob/8bf6fa6b4f525a764e90955c69c0efeecdc74a5b/distribution/packages/src/common/scripts/postinst#L93-L100

2022-02-03 08:31 UTC, okynos commented on indexer/rpm/wazuh-indexer.spec
> +    fi
Nothing to do.

2022-02-03 08:31 UTC, okynos commented on stack/indexer/deb/build_package.sh
> +# Copyright (C) 2015-2021, Wazuh Inc.
v2

2022-02-03 08:31 UTC, okynos commented on stack/indexer/deb/builder.sh
> +# Copyright (C) 2015-2022, Wazuh Inc.
v2

2022-02-03 08:32 UTC, okynos commented on stack/indexer/deb/debian/changelog
> + -- Wazuh, Inc <info@wazuh.com>  Mon, 15 Nov 2021 16:47:07 +0000
It has UNRELEASED tag, required by Debian guidelines.

2022-02-03 08:32 UTC, okynos commented on stack/indexer/deb/debian/copyright
> +    Copyright (C) 2015-2022 Wazuh, Inc <info@wazuh.com>
v2

2022-02-03 08:33 UTC, okynos commented on stack/indexer/deb/debian/postinst
> +        /etc/rc.d/init.d/wazuh-indexer restart > /dev/null 2>&1
Nothing to do.

2022-02-03 08:35 UTC, okynos commented on stack/indexer/deb/debian/postrm
> +# source the default env file
cfb4b3e7

2022-02-03 08:35 UTC, okynos commented on stack/indexer/deb/debian/postinst
> +  # otherwise it is an upgrade
cfb4b3e7

2022-02-03 08:36 UTC, okynos commented on stack/indexer/deb/debian/rules
> +# build-arch and build-indep targets by Bill Allombert 2001
Maybe we could ask to Joey Hess and Craig Small.

2022-02-03 08:37 UTC, okynos commented on stack/indexer/deb/debian/rules
> +export DH_VERBOSE=1
Don't think so https://github.com/wazuh/wazuh-packages/blob/master/debs/SPECS/4.4.0/wazuh-manager/debian/rules#L14

2022-02-03 08:38 UTC, okynos commented on stack/indexer/deb/debian/rules
> +		# copy to target
0d74a751

2022-02-03 08:39 UTC, okynos commented on stack/indexer/rpm/docker/x86_64/Dockerfile
> +
Downgraded to CentOS 7 in v2

2022-02-03 08:39 UTC, okynos commented on indexer/rpm/wazuh-indexer.spec
> +# Wazuh package SPEC
https://github.com/wazuh/wazuh-packages/commit/2ad2a4d3f73601e0c7374c2eb0155229f3e69147

2022-02-03 08:40 UTC, okynos commented on stack/indexer/rpm/wazuh-indexer.spec
> +# Wazuh package SPEC
https://github.com/wazuh/wazuh-packages/commit/2ad2a4d3f73601e0c7374c2eb0155229f3e69147
1fcd99dd

2022-02-03 08:41 UTC, okynos commented on stack/indexer/securityadmin_wrapper.sh
> +HOST="127.0.0.1"
v2

2022-02-03 08:41 UTC, okynos commented on stack/indexer/securityadmin_wrapper.sh
> +PORT="9800"
v2

2022-02-03 08:41 UTC, okynos commented on stack/indexer/securityadmin_wrapper.sh
> +CONFIG_PATH="/etc/wazuh-indexer"
v2

2022-02-03 11:47 UTC, merged