Shellcheck GitHub actions workflow 1
wazuh/wazuh-packages pull request #1385
Opened 2022-03-23 20:01 UTC by fcaffieri

|Related issue|
|---|
|#1351|

## Description
Generating the artifacts according to the changes obtained in the PR on the unattended_installer directory.
Generate the scripts with the builder.sh to later analyze them with ShellCheck

## Logs example

## Tests

[Test Workflow](https://github.com/wazuh/wazuh-packages/pull/1366)

2022-03-23 21:11 UTC, rauldpm approved these changes
LGTM

2022-03-28 15:36 UTC, alberpilot requested changes

2022-03-28 15:36 UTC, alberpilot commented on .github/workflows/pr-reviews.yml
> +name: pr-review
Shellcheck code analysis

2022-03-28 15:36 UTC, alberpilot commented on .github/workflows/pr-reviews.yml
> +          token: ${{ secrets.GITHUB_TOKEN }}
Test if necessary. `secrets.GITHUB_TOKEN`

2022-03-28 15:36 UTC, alberpilot commented on .github/workflows/pr-reviews.yml
> +      - name: Checkout
Remove it

2022-03-29 16:31 UTC, closed without merging