1523 unattended change password api
wazuh/wazuh-packages pull request #1548
Opened 2022-05-16 12:45 UTC by miguelfdez99

|Related issue|
|---|
|#1523|

## Description

The unattended installation did not change the default password for wazuh and wazuh-wui users for the API. It was necessary to implement it.
- The new API password must contain a special character.

## Logs example

- New passwords added to passwords.wazuh file
![2022-05-16_14-35](https://user-images.githubusercontent.com/61159728/168594803-222f54af-e43d-4a3a-888e-63867ed62140.png)
-  wazuh-wui password in file /usr/share/wazuh-dashboard/data/wazuh/config/wazuh.yml
![2022-05-16_14-36](https://user-images.githubusercontent.com/61159728/168594977-249b8cbe-f1df-4baa-9d59-1040d18f0dc8.png)

## Tests

- Distributed
https://devel.ci.wazuh.info/job/Test_unattended_distributed/464/

- All in one
https://ci.wazuh.info/job/Test_unattended/78/
https://ci.wazuh.info/job/Test_unattended/77/
![2022-05-13_15-33](https://user-images.githubusercontent.com/61159728/168593394-8f97eb41-8669-4b4a-a4c9-710e323a12cf.png)

2022-05-19 08:52 UTC, DFolchA requested changes

2022-05-19 08:52 UTC, DFolchA commented on unattended_installer/install_functions/installCommon.sh
> +    password_wazuh=$(cat /tmp/wazuh-install-files/passwords.wazuh | awk -F': ' '{print $2}' | tail -n 6 | head -n 1)
What happens if the user has set the passwords in a different order?

2022-05-19 08:52 UTC, DFolchA commented on unattended_installer/install_functions/installCommon.sh
> +        password_wazuh_wui=$(cat /tmp/wazuh-install-files/passwords.wazuh | awk -F': ' '{print $2}' | tail -n 2 | head -n 1)
Same, what if the user sets the passwords in a different order?

2022-05-19 08:52 UTC, DFolchA commented on unattended_installer/install_functions/installCommon.sh
> +function installCommon_changePasswordAPI() {
This function should be included in the password tool.

2022-05-19 08:52 UTC, DFolchA commented on unattended_installer/install_functions/installCommon.sh
> +function installCommon_updateDashborad_WUI_Password() {
This function should be included in the password tool.

2022-05-20 09:43 UTC, DFolchA requested changes

2022-05-20 09:43 UTC, DFolchA commented on unattended_installer/passwords_tool/passwordsFunctions.sh
> +function passwords_changePasswordAPI() {
We need to add an option to change the API password.

2022-05-20 12:39 UTC, rauldpm requested changes

2022-05-24 08:53 UTC, DFolchA requested changes

2022-05-24 08:53 UTC, DFolchA commented on unattended_installer/passwords_tool/passwordsMain.sh
> +    echo -e "        -ai,  --api-id <currentPassword> <id>"
Avoid options with more than one variable.

2022-05-24 14:03 UTC, DFolchA requested changes

2022-05-25 08:11 UTC, miguelfdez99 commented
Jenkins builds:
 - [Unattended distributed ](https://ci.wazuh.info/job/Test_unattended_distributed/4/) ✅ 
 - All in one:
   - [RedHat 7](https://ci.wazuh.info/job/Test_unattended/91/) ✅ 
   - [RedHat 8](https://ci.wazuh.info/job/Test_unattended/89/) ✅ 
   - [Ubuntu Bionic](https://ci.wazuh.info/job/Test_unattended/86/) ✅ 
   - [Centos7](https://ci.wazuh.info/job/Test_unattended/85/) ✅

2022-05-27 11:04 UTC, DFolchA requested changes

2022-05-27 11:04 UTC, DFolchA commented on unattended_installer/passwords_tool/passwordsFunctions.sh
> +        common_logger -nl $'Changing API user '${nuser}' password'
Use the same notation as the rest of the script:
```
"string ${var} "
```

2022-05-27 11:04 UTC, DFolchA commented on unattended_installer/passwords_tool/passwordsFunctions.sh
> +        common_logger -nl $'API password changed'
same

2022-05-27 11:04 UTC, DFolchA commented on unattended_installer/passwords_tool/passwordsFunctions.sh
> +        common_logger -nl $'The new password for user '${nuser}' is '${password}''
same

2022-05-27 11:04 UTC, DFolchA commented on unattended_installer/passwords_tool/passwordsFunctions.sh
> +        common_logger -nl $'Changing API user '${nuser}' password'
Same

2022-05-27 11:04 UTC, DFolchA commented on unattended_installer/passwords_tool/passwordsFunctions.sh
> +        common_logger -nl $'API password changed'
Same

2022-05-27 11:04 UTC, DFolchA commented on unattended_installer/passwords_tool/passwordsFunctions.sh
> +        echo "ERROR: File /usr/share/wazuh-dashboard/data/wazuh/config/wazuh.yml does not exist"
Use logger

2022-05-31 07:27 UTC, DFolchA approved these changes
LGTM

2022-06-02 15:57 UTC, rauldpm commented
The unattended install checks are getting stuck in the test_check_wazuh_api_status check, this causes the checkruns not to finish and there is no log to show since the connection with the aws worker dies.

It is necessary to add a time limit after which the test must be marked as failed.

Check the manual execution of said test_unattended.py tests

```
[root@ip-172-31-37-212 install]# python3 -m pytest --tb=long test_unattended.py -v -m "wazuh or wazuh_worker or indexer or dashboard"
========================================= test session starts ==========================================
platform linux -- Python 3.6.8, pytest-6.2.5, py-1.11.0, pluggy-1.0.0 -- /bin/python3
cachedir: .pytest_cache
rootdir: /tmp/unattended/tests/unattended/install, configfile: pytest.ini
collected 22 items / 3 deselected / 19 selected                                                        

test_unattended.py::test_check_wazuh_manager_authd PASSED                                        [  5%]
test_unattended.py::test_check_wazuh_manager_db PASSED                                           [ 10%]
test_unattended.py::test_check_wazuh_manager_execd PASSED                                        [ 15%]
test_unattended.py::test_check_wazuh_manager_analysisd PASSED                                    [ 21%]
test_unattended.py::test_check_wazuh_manager_syscheckd PASSED                                    [ 26%]
test_unattended.py::test_check_wazuh_manager_remoted PASSED                                      [ 31%]
test_unattended.py::test_check_wazuh_manager_logcollec PASSED                                    [ 36%]
test_unattended.py::test_check_wazuh_manager_monitord PASSED                                     [ 42%]
test_unattended.py::test_check_wazuh_manager_modulesd PASSED                                     [ 47%]
test_unattended.py::test_check_wazuh_manager_apid PASSED                                         [ 52%]
test_unattended.py::test_check_filebeat_process PASSED                                           [ 57%]
test_unattended.py::test_check_indexer_process PASSED                                            [ 63%]
test_unattended.py::test_check_dashboard_process PASSED                                          [ 68%]
test_unattended.py::test_check_indexer_cluster_status_not_red PASSED                             [ 73%]
test_unattended.py::test_check_dashboard_status PASSED                                           [ 78%]
test_unattended.py::test_check_wazuh_api_status 


```

2022-06-02 16:06 UTC, DFolchA commented on unattended_installer/install_functions/dashboard.sh
> +    passwords_updateDashborad_WUI_Password
Done [39d59da](https://github.com/wazuh/wazuh-packages/pull/1548/commits/39d59da63daacf4e3ea20cbbad770b8624917e73)

2022-06-02 16:06 UTC, DFolchA commented on unattended_installer/install_functions/installCommon.sh
> +        api_file="/tmp/wazuh-install-files/passwords-api.wazuh"
Done [39d59da](https://github.com/wazuh/wazuh-packages/pull/1548/commits/39d59da63daacf4e3ea20cbbad770b8624917e73)

2022-06-08 11:25 UTC, alberpilot approved these changes
LGTM

2022-06-08 11:26 UTC, merged