Add tmp (directory) parameter
wazuh/wazuh-packages pull request #1629
Opened 2022-06-06 19:33 UTC by teddytpc1

|Related issue|
|---|
|#1617|

## Description
This PR modifies the `wazuh-certs-tool` to add the `-tmp` option in order to specify the tmp directory.

## Tests
It was tested along with the `-a`, `-A`, `-ca`, `-wi`, `-wd`, `-ws` options before and after the `-tmp`.

2022-07-14 07:23 UTC, okynos approved these changes

2022-07-22 13:25 UTC, DFolchA requested changes

2022-07-22 13:25 UTC, DFolchA commented on unattended_installer/cert_tool/certFunctions.sh
> +    eval "rm -f ${tmp_path}/*.csr ${debug}"
Please use a more descriptive variable name, for example, `cert_tmp_path` to avoid possible confusion.

2022-07-25 14:56 UTC, okynos approved these changes

2022-07-27 11:04 UTC, alberpilot approved these changes

2022-08-01 09:51 UTC, DFolchA approved these changes
lgtm

2022-08-01 10:59 UTC, okynos approved these changes

2022-08-01 11:00 UTC, merged