Add support to RedHat 9 in unattended
wazuh/wazuh-packages pull request #1680
Opened 2022-06-23 10:02 UTC by okynos

Hello!

We have include a light modifications to the unattended to include RHEL 9 support.

2022-06-23 10:12 UTC, alberpilot requested changes
Please review

2022-06-23 10:12 UTC, alberpilot commented on unattended_installer/install_functions/checks.sh
> -    if ([ "${DIST_NAME}" == "ubuntu" ]) && ([ "${DIST_VER}" -ne "16" ] && [ "${DIST_VER}" -ne "18" ] && [ "${DIST_VER}" -ne "20" ] && [ "${DIST_VER}" -ne "22" ]); then
Restore this please, it must be a `0.4` version, so this needs to be checked.

2022-06-24 10:00 UTC, DFolchA approved these changes
LGTM

2022-06-24 11:10 UTC, alberpilot approved these changes

2022-06-24 11:12 UTC, merged