Fix Wazuh installation assistant AIO deployment in Fedora 36
wazuh/wazuh-packages pull request #1779
Opened 2022-08-08 09:46 UTC by miguelfdez99

|Related issue|
|---|
|closes #1702|

## Description

The error occurred because the function checks if the dependency openssl is installed with this command.
````
[root@fedora36 vagrant]# openssl
bash: openssl: command not found
[root@fedora36 vagrant]# yum list installed 2>/dev/null | grep openssl
openssl-devel.x86_64                 1:3.0.5-1.fc36                    @updates 
openssl-libs.x86_64                  1:3.0.5-1.fc36                    @updates 
````
The result is that the dependency is installed but actually it is not. We can not run OpenSSL unless openssl.x86_64 is installed.
That is why we need an extra check for the openssl dependency.
## Logs example

````
[root@fedora36 vagrant]# bash wazuh-install.sh -a -i
08/08/2022 09:04:44 INFO: Starting Wazuh installation assistant. Wazuh version: 4.3.6
08/08/2022 09:04:44 INFO: Verbose logging redirected to /var/log/wazuh-install.log
08/08/2022 09:04:45 WARNING: Hardware and system checks ignored.
08/08/2022 09:04:46 INFO: --- Dependencies ---
08/08/2022 09:04:46 INFO: Installing openssl.
08/08/2022 09:04:48 INFO: Wazuh repository added.
08/08/2022 09:04:48 INFO: --- Configuration files ---
08/08/2022 09:04:48 INFO: Generating configuration files.
08/08/2022 09:04:50 INFO: Created wazuh-install-files.tar. It contains the Wazuh cluster key, certificates, and passwords necessary for installation.
08/08/2022 09:04:50 INFO: --- Wazuh indexer ---
08/08/2022 09:04:50 INFO: Starting Wazuh indexer installation.
08/08/2022 09:05:39 INFO: Wazuh indexer installation finished.
08/08/2022 09:05:39 INFO: Wazuh indexer post-install configuration finished.
08/08/2022 09:05:39 INFO: Starting service wazuh-indexer.
08/08/2022 09:05:47 INFO: wazuh-indexer service started.
08/08/2022 09:05:47 INFO: Initializing Wazuh indexer cluster security settings.
08/08/2022 09:05:52 INFO: Wazuh indexer cluster initialized.
08/08/2022 09:05:52 INFO: --- Wazuh server ---
08/08/2022 09:05:52 INFO: Starting the Wazuh manager installation.
08/08/2022 09:06:23 INFO: Wazuh manager installation finished.
08/08/2022 09:06:23 INFO: Starting service wazuh-manager.
08/08/2022 09:06:34 INFO: wazuh-manager service started.
08/08/2022 09:06:34 INFO: Starting Filebeat installation.
08/08/2022 09:06:39 INFO: Filebeat installation finished.
08/08/2022 09:06:39 INFO: Filebeat post-install configuration finished.
08/08/2022 09:06:39 INFO: Starting service filebeat.
08/08/2022 09:06:40 INFO: filebeat service started.
08/08/2022 09:06:40 INFO: --- Wazuh dashboard ---
08/08/2022 09:06:40 INFO: Starting Wazuh dashboard installation.
08/08/2022 09:07:22 INFO: Wazuh dashboard installation finished.
08/08/2022 09:07:22 INFO: Wazuh dashboard post-install configuration finished.
08/08/2022 09:07:22 INFO: Starting service wazuh-dashboard.
08/08/2022 09:07:22 INFO: wazuh-dashboard service started.
08/08/2022 09:07:46 INFO: Initializing Wazuh dashboard web application.
08/08/2022 09:07:46 INFO: Wazuh dashboard web application initialized.
08/08/2022 09:07:46 INFO: --- Summary ---
08/08/2022 09:07:46 INFO: You can access the web interface https://<wazuh-dashboard-ip>
    User: admin
    Password: R.KXvtxRiy+j2J?hOWAl6gWUYi?n32aJ
08/08/2022 09:07:46 INFO: Installation finished.
````
````
[root@fedora36 vagrant]# yum list installed 2>/dev/null | grep openssl.x86
openssl.x86_64                       1:3.0.5-1.fc36                    @updates 
````

2022-08-08 10:16 UTC, okynos requested changes
Minor change

2022-08-08 10:16 UTC, okynos commented on unattended_installer/install_functions/installCommon.sh
> +                if ! yum list installed 2>/dev/null | grep -q "${dep}".x86;then
```suggestion
                if ! yum list installed 2>/dev/null | grep -q "${dep}\.";then
```

2022-08-08 10:35 UTC, miguelfdez99 commented on unattended_installer/install_functions/installCommon.sh
> +                if ! yum list installed 2>/dev/null | grep -q "${dep}".x86;then
Done https://github.com/wazuh/wazuh-packages/pull/1779/commits/fb652b2b32ffd46d1a284cb767dc187a6ded0cc2

2022-08-30 06:30 UTC, DFolchA requested changes

2022-08-30 06:30 UTC, DFolchA commented on unattended_installer/install_functions/installCommon.sh
> +                not_installed+=("${dep}")
Check indent

2022-08-30 06:39 UTC, miguelfdez99 commented on unattended_installer/install_functions/installCommon.sh
> +                not_installed+=("${dep}")
Done https://github.com/wazuh/wazuh-packages/pull/1779/commits/e7ac44ea17638aaa32e3e7979932c5d11bcb4b76

2022-08-30 07:26 UTC, okynos approved these changes

2022-08-30 07:28 UTC, DFolchA approved these changes
lgtm

2022-08-30 07:28 UTC, merged