Bump 3.13.6
wazuh/wazuh-packages pull request #1841
Opened 2022-09-08 16:01 UTC by c-bordon

|Related issue|
|---|
||

## Description

Bump for 3.13.6

## Logs example

## Tests
DEB: https://ci.wazuh.info/view/Packages/job/Packages_builder/110999/console
RPM: https://ci.wazuh.info/view/Packages/job/Packages_builder/110998/console

- Build the package in any supported platform
  - [x] Linux
  - [ ] Windows
  - [ ] macOS
  - [ ] Solaris
  - [ ] AIX
  - [ ] HP-UX
- [ ] Package installation
- [ ] Package upgrade
- [ ] Package downgrade
- [ ] Package remove
- [ ] Package install/remove/install
- [ ] Change added to CHANGELOG.md

- Tests for Linux RPM
  - [x] Build the package for x86_64
  - [ ] Build the package for i386
  - [ ] Build the package for armhf
  - [ ] Build the package for aarch64
  - [ ] `%files` section is correctly updated if necessary
- Tests for Linux deb
  - [x] Build the package for x86_64
  - [ ] Build the package for i386
  - [ ] Build the package for armhf
  - [ ] Build the package for aarch64
  - [ ] Package install/remove/install
  - [ ] Package install/purge/install
  - [ ] Check file permissions after installing the package
- Tests for macOS
  - [ ] Test the package from macOS Sierra to Mojave
- Tests for Solaris
  - [ ] Test the package on Solaris 10
  - [ ] Test the package on Solaris 11
  - [ ] Check file permissions on Solaris 11 template
- Tests for IBM AIX
  - [ ] `%files` section is correctly updated if necessary
  - [ ] Check the changes from IBM AIX 5 to 7

2022-09-08 21:22 UTC, rauldpm requested changes
Check the rest of the files, there should be more changes to bump, like Macos, for reference see https://github.com/wazuh/wazuh-packages/pull/1788/files

2022-09-09 11:01 UTC, DFolchA approved these changes

2022-09-09 12:23 UTC, rauldpm requested changes

2022-09-09 12:23 UTC, rauldpm commented on debs/SPECS/3.13.6/wazuh-api/debian/control
> +Depends: ${shlibs:Depends}, npm, nodejs (>= 4.6.1), wazuh-manager (>= 3.13.5), wazuh-manager (<< 3.13.6), curl
Review versions in control files, compare them with previous release if needed.

```suggestion
Depends: ${shlibs:Depends}, npm, nodejs (>= 4.6.1), wazuh-manager (>= 3.13.6), wazuh-manager (<< 3.13.7), curl
```

2022-09-09 12:36 UTC, rauldpm approved these changes
LGTM

2022-09-12 13:49 UTC, DFolchA approved these changes

2022-09-12 15:03 UTC, okynos approved these changes

2022-09-12 15:03 UTC, merged