fix: Symblic link to /etc/init.d
wazuh/wazuh-packages pull request #1905
Opened 2022-10-24 12:58 UTC by GabrielEValenzuela

|Related issue|
|---|
| [#14924](https://github.com/wazuh/wazuh/issues/14924)  |

# Solution report

## Goal
This report has for goal to make a summary of the implemented solution.

## Issue research
This issue is produced by a wrong symbolink in the openSUSE Leap 15.4 distribution in the RPM packages.

When post-installation, it try to enable the service (agent or manager). It raised an error because openSUSE try to create a symbolic link to `/etc/init.d/rc2.d` it doesn't exist. This problem has been found in this [forum thread](https://forums.opensuse.org/showthread.php/569830-Can-systemctl-start-elasticsearch-but-not-systemctl-enable-it), where the explain of the reason it's because the package it's an original openSUSE package so it tries to use `/etc/init.d/rc2.d` which directory belongs to the old SystemV ways of doing but in openSUSE that directory is no longer in use and most probably not available anymore.

## Test description & results
To solve this problem we create a symbolic link to the correct path and then enable the service. 

We attach the ouput of this fix, with a new installation and upgrade from 4.3 to 4.4

```bash
// Fresh install
# rpm -i wazuh-agent-4.3.9-rev.fix.x86_64.rpm 
# systemctl is-enabled wazuh-agent.service 
enabled
# /var/ossec/bin/wazuh-control info
WAZUH_VERSION="v4.3.9"
WAZUH_REVISION="40322"
WAZUH_TYPE="agent"

//Update de 4.3 a 4.4 por package
# rpm -U wazuh-agent-4.4.0-rev.fix.x86_64.rpm 
# systemctl is-enabled wazuh-agent.service 
enabled
# /var/ossec/bin/wazuh-control info
WAZUH_VERSION="v4.4.0"
WAZUH_REVISION="40400"
WAZUH_TYPE="agent"
```

In both cases, the packages were built locally, with this command:

```bash
./generate_rpm_package.sh -b 4.x --packages-branch 4.x -s /tmp -t type -a x86_64 -r rev.fix --dev
```

## Conclutions
The proposed solution is similar to other symbolic links used in other operating systems. Also, it is important to remember that, the `ln` command does not care if the source file exists, so if there is an error in the path, it will not complain and it is relative to the parent directory of the symbolic link and not where `ln` is executed.

- Build the package in any supported platform
  - [X] Linux
  - [ ] Windows
  - [ ] macOS
  - [ ] Solaris
  - [ ] AIX
  - [ ] HP-UX
- [X] Package installation
- [X] Package upgrade
- [ ] Package downgrade
- [ ] Package remove
- [ ] Package install/remove/install
- [ ] Change added to CHANGELOG.md

- Tests for Linux RPM
  - [X] Build the package for x86_64
  - [ ] Build the package for i386
  - [ ] Build the package for armhf
  - [ ] Build the package for aarch64
  - [ ] `%files` section is correctly updated if necessary
- Tests for Linux deb
  - [ ] Build the package for x86_64
  - [ ] Build the package for i386
  - [ ] Build the package for armhf
  - [ ] Build the package for aarch64
  - [ ] Package install/remove/install
  - [ ] Package install/purge/install
  - [ ] Check file permissions after installing the package
- Tests for macOS
  - [ ] Test the package from macOS Sierra to Mojave
- Tests for Solaris
  - [ ] Test the package on Solaris 10
  - [ ] Test the package on Solaris 11
  - [ ] Check file permissions on Solaris 11 template
- Tests for IBM AIX
  - [ ] `%files` section is correctly updated if necessary
  - [ ] Check the changes from IBM AIX 5 to 7

2022-10-25 15:02 UTC, chemamartinez approved these changes
LGTM

2022-11-03 09:29 UTC, chemamartinez approved these changes

2022-11-09 11:56 UTC, jmv74211 approved these changes
## QA review

- **Type**: Manual testing.
- **Status**: Approved  🟢 
- **Testing issue**: https://github.com/wazuh/wazuh-qa/issues/3399
- **Comments**:  https://github.com/wazuh/wazuh-qa/issues/3399#issuecomment-1308609129

2022-11-22 10:44 UTC, DFolchA requested changes
A few changes were requested, and please test these packages in old versions of OpenSUSE and SUSE.

2022-11-22 10:44 UTC, DFolchA commented on rpms/SPECS/wazuh-agent.spec
> +    ln -sf ../wazuh-agent /etc/init.d/wazuh-agent
Please do not use relative paths.

2022-11-22 10:44 UTC, DFolchA commented on rpms/SPECS/wazuh-manager.spec
> +    ln -sf ../wazuh-manager /etc/init.d/wazuh-manager
Please do not use relative paths.

2022-11-22 10:44 UTC, DFolchA commented on rpms/SPECS/wazuh-manager.spec
> +  if [ ! -d /etc/init.d/wazuh-manager ]; then
Why are you checking if a file is a directory?

2022-11-23 10:47 UTC, GabrielEValenzuela commented on rpms/SPECS/wazuh-agent.spec
> +    ln -sf ../wazuh-agent /etc/init.d/wazuh-agent
Done. Thank you :)

2022-11-23 13:28 UTC, DFolchA requested changes

2022-11-23 13:28 UTC, DFolchA commented on rpms/SPECS/wazuh-agent.spec
> +  ln -sf ../wazuh-agent /etc/init.d/wazuh-agent
Please do not use relative paths.

2022-11-23 13:28 UTC, DFolchA commented on rpms/SPECS/wazuh-manager.spec
> +  ln -sf ../wazuh-manager /etc/init.d/wazuh-manager
Please do not use relative paths.

2022-11-25 15:15 UTC, chemamartinez commented on rpms/SPECS/wazuh-agent.spec
> +      rm /etc/init.d/wazuh-agent
```suggestion
      rm -f /etc/init.d/wazuh-agent
```

2022-11-25 15:16 UTC, chemamartinez commented on rpms/SPECS/wazuh-manager.spec
> +      rm /etc/init.d/wazuh-manager
```suggestion
      rm -f /etc/init.d/wazuh-manager
```

2022-11-28 08:37 UTC, DFolchA requested changes

2022-11-28 08:37 UTC, DFolchA commented on rpms/SPECS/wazuh-agent.spec
> +  if [ ! -z "$sles" ] && [ $(ps --no-headers -o comm 1) == "systemd" ]; then
Please use `-n` instead of `! -z`.

2022-11-28 08:37 UTC, DFolchA commented on rpms/SPECS/wazuh-manager.spec
> +  if [ ! -z "$sles" ] && [ $(ps --no-headers -o comm 1) == "systemd" ]; then
Please use `-n` instead of `! -z`.

2022-11-28 08:37 UTC, DFolchA commented on rpms/SPECS/wazuh-manager.spec
> +    #If it's an upgrade and there is a service file in /etc/init.d/ we deleted.
This comment is not accurate as this section will be executed in both install and upgrade.

2022-11-28 09:28 UTC, GabrielEValenzuela commented on rpms/SPECS/wazuh-agent.spec
> +  if [ ! -z "$sles" ] && [ $(ps --no-headers -o comm 1) == "systemd" ]; then
Thanks. It's done.

2022-11-28 14:56 UTC, DFolchA requested changes

2022-11-28 14:56 UTC, DFolchA commented on rpms/SPECS/wazuh-agent.spec
> +sles=""
Wrong indentation.

2022-11-28 14:56 UTC, DFolchA commented on rpms/SPECS/wazuh-manager.spec
> +sles=""
Wrong indentation.

2022-11-28 15:02 UTC, GabrielEValenzuela commented on rpms/SPECS/wazuh-agent.spec
> +sles=""
Thank you !

2022-11-28 15:03 UTC, DFolchA approved these changes

2022-11-28 16:16 UTC, alberpilot approved these changes
LGTM

2022-11-29 08:23 UTC, jmv74211 approved these changes
## QA review

- **Type**: Manual testing.
- **Status**: Approved  🟢 
- **Testing issue**: https://github.com/wazuh/wazuh-qa/issues/3399
- **Comments**:  Initially the development was tested [here](https://github.com/wazuh/wazuh-qa/issues/3399#issuecomment-1308609129 ), but then new changes were added and manually tested [here](https://github.com/wazuh/wazuh-packages/pull/1905#issuecomment-1329192969). @Deblintrake09 (who did the previous testing) has supervised that testing and claims that it is sufficient to pass the PR.

2022-11-29 08:42 UTC, merged