Removed init.d service for Wazuh dashboard rpm
wazuh/wazuh-packages pull request #1987
Opened 2022-12-14 19:36 UTC by c-bordon

|Related issue|
|---|
|https://github.com/wazuh/wazuh-packages/issues/1975|

## Description

Due to problems in managing services between init.d and systemd in RPM systems, especially in the use of `service wazuh-dashboard status`, it was decided to apply the same solution applied for Red Hat 9 in this [PR](https://github.com/wazuh/wazuh-packages/pull/1898/files).

Removing the /etc/init.d/wazuh-dashboard file forces the system to redirect calls from init.d to systemd.

## Logs example

## Tests

- Build the package in any supported platform
  - [x] Linux
  - [ ] Windows
  - [ ] macOS
  - [ ] Solaris
  - [ ] AIX
  - [ ] HP-UX
- [x] Package installation
- [ ] Package upgrade
- [ ] Package downgrade
- [ ] Package remove
- [ ] Package install/remove/install
- [ ] Change added to CHANGELOG.md

- Tests for Linux RPM
  - [x] Build the package for x86_64
  - [ ] Build the package for i386
  - [ ] Build the package for armhf
  - [ ] Build the package for aarch64
  - [ ] `%files` section is correctly updated if necessary
- Tests for Linux deb
  - [ ] Build the package for x86_64
  - [ ] Build the package for i386
  - [ ] Build the package for armhf
  - [ ] Build the package for aarch64
  - [ ] Package install/remove/install
  - [ ] Package install/purge/install
  - [ ] Check file permissions after installing the package
- Tests for macOS
  - [ ] Test the package from macOS Sierra to Mojave
- Tests for Solaris
  - [ ] Test the package on Solaris 10
  - [ ] Test the package on Solaris 11
  - [ ] Check file permissions on Solaris 11 template
- Tests for IBM AIX
  - [ ] `%files` section is correctly updated if necessary
  - [ ] Check the changes from IBM AIX 5 to 7

2022-12-14 19:36 UTC, c-bordon commented
### OVA
<details><summary>Service</summary>

```
[root@wazuh-server ~]# mv /etc/init.d/wazuh-dashboard /etc/init.d/wazuh-dashboard.save
[root@wazuh-server ~]# service wazuh-dashboard status                                 
Redirecting to /bin/systemctl status wazuh-dashboard.service
● wazuh-dashboard.service - wazuh-dashboard
   Loaded: loaded (/etc/systemd/system/wazuh-dashboard.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2022-12-14 13:04:30 UTC; 7min ago
 Main PID: 3613 (node)
   CGroup: /system.slice/wazuh-dashboard.service
           └─3613 /usr/share/wazuh-dashboard/bin/../node/bin/node --no-warnings --max-http-header-size=65536 --unhandled-rejections=warn /usr/share/wazuh-dashboard/bin/../src/cli/dist -c /etc/wazuh-dashboard/opensearch_dashboards.yml

Dec 14 13:04:33 wazuh-server opensearch-dashboards[3613]: {"type":"log","@timestamp":"2022-12-14T13:04:33Z","tags":["info","plugins-service"],"pid":3613,"message":"Plugin \"visTypeXy\" is disabled."}
Dec 14 13:04:33 wazuh-server opensearch-dashboards[3613]: {"type":"log","@timestamp":"2022-12-14T13:04:33Z","tags":["info","plugins-service"],"pid":3613,"message":"Plugin \"wizard\" is disabled."}
Dec 14 13:04:33 wazuh-server opensearch-dashboards[3613]: {"type":"log","@timestamp":"2022-12-14T13:04:33Z","tags":["warning","config","deprecation"],"pid":3613,"message":"\"opensearch.requestHeadersWhitelist\" is depre...rsAllowlist\""}
Dec 14 13:04:33 wazuh-server opensearch-dashboards[3613]: {"type":"log","@timestamp":"2022-12-14T13:04:33Z","tags":["info","plugins-system"],"pid":3613,"message":"Setting up [44] plugins: [alertingDashboards,usageCollec...embeddable,expr
Dec 14 13:04:33 wazuh-server opensearch-dashboards[3613]: {"type":"log","@timestamp":"2022-12-14T13:04:33Z","tags":["info","savedobjects-service"],"pid":3613,"message":"Waiting until all OpenSearch nodes are compatible ...migrations..."}
Dec 14 13:04:33 wazuh-server opensearch-dashboards[3613]: {"type":"log","@timestamp":"2022-12-14T13:04:33Z","tags":["info","savedobjects-service"],"pid":3613,"message":"Starting saved objects migrations"}
Dec 14 13:04:33 wazuh-server opensearch-dashboards[3613]: {"type":"log","@timestamp":"2022-12-14T13:04:33Z","tags":["info","plugins-system"],"pid":3613,"message":"Starting [44] plugins: [alertingDashboards,usageCollecti...beddable,expres
Dec 14 13:04:33 wazuh-server opensearch-dashboards[3613]: {"type":"log","@timestamp":"2022-12-14T13:04:33Z","tags":["listening","info"],"pid":3613,"message":"Server running at https://0.0.0.0:443"}
Dec 14 13:04:34 wazuh-server opensearch-dashboards[3613]: {"type":"log","@timestamp":"2022-12-14T13:04:34Z","tags":["info","http","server","OpenSearchDashboards"],"pid":3613,"message":"http server running at https://0.0.0.0:443"}
Hint: Some lines were ellipsized, use -l to show in full.
[root@wazuh-server ~]# service wazuh-dashboard stop
Redirecting to /bin/systemctl stop wazuh-dashboard.service
[root@wazuh-server ~]# service wazuh-dashboard status
Redirecting to /bin/systemctl status wazuh-dashboard.service
● wazuh-dashboard.service - wazuh-dashboard
   Loaded: loaded (/etc/systemd/system/wazuh-dashboard.service; enabled; vendor preset: disabled)
   Active: inactive (dead) since Wed 2022-12-14 13:12:16 UTC; 3s ago
  Process: 3613 ExecStart=/usr/share/wazuh-dashboard/bin/opensearch-dashboards -c /etc/wazuh-dashboard/opensearch_dashboards.yml (code=exited, status=0/SUCCESS)
 Main PID: 3613 (code=exited, status=0/SUCCESS)

Dec 14 13:04:33 wazuh-server opensearch-dashboards[3613]: {"type":"log","@timestamp":"2022-12-14T13:04:33Z","tags":["info","plugins-service"],"pid":3613,"message":"Plugin \"visTypeXy\" is disabled."}
Dec 14 13:04:33 wazuh-server opensearch-dashboards[3613]: {"type":"log","@timestamp":"2022-12-14T13:04:33Z","tags":["info","plugins-service"],"pid":3613,"message":"Plugin \"wizard\" is disabled."}
Dec 14 13:04:33 wazuh-server opensearch-dashboards[3613]: {"type":"log","@timestamp":"2022-12-14T13:04:33Z","tags":["warning","config","deprecation"],"pid":3613,"message":"\"opensearch.requestHeadersWhitelist\" is depre...rsAllowlist\""}
Dec 14 13:04:33 wazuh-server opensearch-dashboards[3613]: {"type":"log","@timestamp":"2022-12-14T13:04:33Z","tags":["info","plugins-system"],"pid":3613,"message":"Setting up [44] plugins: [alertingDashboards,usageCollec...embeddable,expr
Dec 14 13:04:33 wazuh-server opensearch-dashboards[3613]: {"type":"log","@timestamp":"2022-12-14T13:04:33Z","tags":["info","savedobjects-service"],"pid":3613,"message":"Waiting until all OpenSearch nodes are compatible ...migrations..."}
Dec 14 13:04:33 wazuh-server opensearch-dashboards[3613]: {"type":"log","@timestamp":"2022-12-14T13:04:33Z","tags":["info","savedobjects-service"],"pid":3613,"message":"Starting saved objects migrations"}
Dec 14 13:04:33 wazuh-server opensearch-dashboards[3613]: {"type":"log","@timestamp":"2022-12-14T13:04:33Z","tags":["info","plugins-system"],"pid":3613,"message":"Starting [44] plugins: [alertingDashboards,usageCollecti...beddable,expres
Dec 14 13:04:33 wazuh-server opensearch-dashboards[3613]: {"type":"log","@timestamp":"2022-12-14T13:04:33Z","tags":["listening","info"],"pid":3613,"message":"Server running at https://0.0.0.0:443"}
Dec 14 13:04:34 wazuh-server opensearch-dashboards[3613]: {"type":"log","@timestamp":"2022-12-14T13:04:34Z","tags":["info","http","server","OpenSearchDashboards"],"pid":3613,"message":"http server running at https://0.0.0.0:443"}
Dec 14 13:12:16 wazuh-server opensearch-dashboards[3613]: {"type":"log","@timestamp":"2022-12-14T13:12:16Z","tags":["info","plugins-system"],"pid":3613,"message":"Stopping all plugins."}
Hint: Some lines were ellipsized, use -l to show in full.
[root@wazuh-server ~]# service wazuh-dashboard start
Redirecting to /bin/systemctl start wazuh-dashboard.service
[root@wazuh-server ~]# service wazuh-dashboard status
Redirecting to /bin/systemctl status wazuh-dashboard.service
● wazuh-dashboard.service - wazuh-dashboard
   Loaded: loaded (/etc/systemd/system/wazuh-dashboard.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2022-12-14 13:12:22 UTC; 2s ago
 Main PID: 3744 (node)
   CGroup: /system.slice/wazuh-dashboard.service
           └─3744 /usr/share/wazuh-dashboard/bin/../node/bin/node --no-warnings --max-http-header-size=65536 --unhandled-rejections=warn /usr/share/wazuh-dashboard/bin/../src/cli/dist -c /etc/wazuh-dashboard/opensearch_dashboards.yml
[root@wazuh-server ~]# service wazuh-dashboard status
Redirecting to /bin/systemctl status wazuh-dashboard.service
● wazuh-dashboard.service - wazuh-dashboard
   Loaded: loaded (/etc/systemd/system/wazuh-dashboard.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2022-12-14 13:12:22 UTC; 4s ago
 Main PID: 3744 (node)
   CGroup: /system.slice/wazuh-dashboard.service
           └─3744 /usr/share/wazuh-dashboard/bin/../node/bin/node --no-warnings --max-http-header-size=65536 --unhandled-rejections=warn /usr/share/wazuh-dashboard/bin/../src/cli/dist -c /etc/wazuh-dashboard/opensearch_dashboards.yml

Dec 14 13:12:25 wazuh-server opensearch-dashboards[3744]: {"type":"log","@timestamp":"2022-12-14T13:12:25Z","tags":["info","plugins-service"],"pid":3744,"message":"Plugin \"visTypeXy\" is disabled."}
Dec 14 13:12:25 wazuh-server opensearch-dashboards[3744]: {"type":"log","@timestamp":"2022-12-14T13:12:25Z","tags":["info","plugins-service"],"pid":3744,"message":"Plugin \"wizard\" is disabled."}
Dec 14 13:12:25 wazuh-server opensearch-dashboards[3744]: {"type":"log","@timestamp":"2022-12-14T13:12:25Z","tags":["warning","config","deprecation"],"pid":3744,"message":"\"opensearch.requestHeadersWhitelist\" is depre...rsAllowlist\""}
Dec 14 13:12:26 wazuh-server opensearch-dashboards[3744]: {"type":"log","@timestamp":"2022-12-14T13:12:26Z","tags":["info","plugins-system"],"pid":3744,"message":"Setting up [44] plugins: [alertingDashboards,usageCollec...embeddable,expr
Dec 14 13:12:26 wazuh-server [...]

2022-12-14 19:36 UTC, c-bordon commented
### Red Hat 7
<details><summary>Service</summary>

```
[root@redhat-7 ~]# ./script.sh rpm service dashboard
Redirecting to /bin/systemctl start wazuh-dashboard.service
Redirecting to /bin/systemctl status wazuh-dashboard.service
Redirecting to /bin/systemctl restart wazuh-dashboard.service
Redirecting to /bin/systemctl status wazuh-dashboard.service
Redirecting to /bin/systemctl condrestart wazuh-dashboard.service
Redirecting to /bin/systemctl status wazuh-dashboard.service
Redirecting to /bin/systemctl try-restart wazuh-dashboard.service
Redirecting to /bin/systemctl status wazuh-dashboard.service
Redirecting to /bin/systemctl force-reload wazuh-dashboard.service
Redirecting to /bin/systemctl status wazuh-dashboard.service
Redirecting to /bin/systemctl stop wazuh-dashboard.service
Redirecting to /bin/systemctl status wazuh-dashboard.service

testing service option start
-----------------------------
Service wazuh-dashboard status
-----------------------------
● wazuh-dashboard.service - wazuh-dashboard
   Loaded: loaded (/etc/systemd/system/wazuh-dashboard.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2022-12-14 17:02:13 UTC; 17s ago
 Main PID: 6866 (node)
   CGroup: /system.slice/wazuh-dashboard.service
           └─6866 /usr/share/wazuh-dashboard/bin/../node/bin/node --no-warnings --max-http-header-size=65536 --unhandled-rejections=warn /usr/share/wazuh-dashboard/bin/../src/cli/dist -c /etc/wazuh-dashboard/opensearch_dashboards.yml

Dec 14 17:02:17 redhat-7 opensearch-dashboards[6866]: {"type":"log","@timestamp":"2022-12-14T17:02:17Z","tags":["info","savedobjects-service"],"pid":6866,"message":"Waiting until all OpenSearch nodes are compatible with OpenSearch Dashboards before starting saved objects migrations..."}
Dec 14 17:02:17 redhat-7 opensearch-dashboards[6866]: {"type":"log","@timestamp":"2022-12-14T17:02:17Z","tags":["info","savedobjects-service"],"pid":6866,"message":"Starting saved objects migrations"}
Dec 14 17:02:17 redhat-7 opensearch-dashboards[6866]: {"type":"log","@timestamp":"2022-12-14T17:02:17Z","tags":["info","savedobjects-service"],"pid":6866,"message":"Creating index .kibana_1."}
Dec 14 17:02:17 redhat-7 opensearch-dashboards[6866]: {"type":"log","@timestamp":"2022-12-14T17:02:17Z","tags":["info","savedobjects-service"],"pid":6866,"message":"Pointing alias .kibana to .kibana_1."}
Dec 14 17:02:17 redhat-7 opensearch-dashboards[6866]: {"type":"log","@timestamp":"2022-12-14T17:02:17Z","tags":["info","savedobjects-service"],"pid":6866,"message":"Finished in 141ms."}
Dec 14 17:02:17 redhat-7 opensearch-dashboards[6866]: {"type":"log","@timestamp":"2022-12-14T17:02:17Z","tags":["info","plugins-system"],"pid":6866,"message":"Starting [44] plugins: [usageCollection,opensearchDashboardsUsageCollection,opensearchDashboardsLegacy,mapsLegacy,alertingDashboards,share,opensearchUiShared,legacyExport,embeddable,expressions,data,home,console,apmOss,management,indexPatternManagement,advancedSettings,savedObjects,reportsDashboards,securityDashboards,dashboard,visualizations,visTypeVega,visTypeTimeline,timeline,visTypeTable,visTypeMarkdown,tileMap,regionMap,customImportMapDashboards,inputControlVis,visualize,ganttChartDashboards,indexManagementDashboards,notificationsDashboards,charts,visTypeVislib,visTypeTimeseries,visTypeTagcloud,visTypeMetric,discover,wazuh,savedObjectsManagement,bfetch]"}
Dec 14 17:02:18 redhat-7 opensearch-dashboards[6866]: {"type":"log","@timestamp":"2022-12-14T17:02:18Z","tags":["listening","info"],"pid":6866,"message":"Server running at https://0.0.0.0:443"}
Dec 14 17:02:18 redhat-7 opensearch-dashboards[6866]: {"type":"log","@timestamp":"2022-12-14T17:02:18Z","tags":["info","http","server","OpenSearchDashboards"],"pid":6866,"message":"http server running at https://0.0.0.0:443"}
Dec 14 17:02:18 redhat-7 opensearch-dashboards[6866]: {"type":"log","@timestamp":"2022-12-14T17:02:18Z","tags":["error","opensearch","data"],"pid":6866,"message":"[ResponseError]: Response Error"}
Dec 14 17:02:18 redhat-7 opensearch-dashboards[6866]: {"type":"log","@timestamp":"2022-12-14T17:02:18Z","tags":["error","opensearch","data"],"pid":6866,"message":"[ResponseError]: Response Error"}
-----------------------------
testing service option restart
-----------------------------
Service wazuh-dashboard status
-----------------------------
● wazuh-dashboard.service - wazuh-dashboard
   Loaded: loaded (/etc/systemd/system/wazuh-dashboard.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2022-12-14 17:02:40 UTC; 18ms ago
 Main PID: 6941 (node)
   CGroup: /system.slice/wazuh-dashboard.service
           └─6941 /usr/share/wazuh-dashboard/bin/../node/bin/node --no-warnings --max-http-header-size=65536 --unhandled-rejections=warn /usr/share/wazuh-dashboard/bin/../src/cli/dist -c /etc/wazuh-dashboard/opensearch_dashboards.yml

Dec 14 17:02:40 redhat-7 systemd[1]: Started wazuh-dashboard.
-----------------------------
testing service option condrestart
-----------------------------
Service wazuh-dashboard status
-----------------------------
● wazuh-dashboard.service - wazuh-dashboard
   Loaded: loaded (/etc/systemd/system/wazuh-dashboard.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2022-12-14 17:02:51 UTC; 17ms ago
 Main PID: 6990 (node)
   CGroup: /system.slice/wazuh-dashboard.service
           └─6990 /usr/share/wazuh-dashboard/bin/../node/bin/node --no-warnings --max-http-header-size=65536 --unhandled-rejections=warn /usr/share/wazuh-dashboard/bin/../src/cli/dist -c /etc/wazuh-dashboard/opensearch_dashboards.yml

Dec 14 17:02:51 redhat-7 systemd[1]: Started wazuh-dashboard.
-----------------------------
testing service option try-restart
-----------------------------
Service wazuh-dashboard status
-----------------------------
● wazuh-dashboard.service - wazuh-dashboard
   Loaded: loaded (/etc/systemd/system/wazuh-dashboard.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2022-12-14 17:03:01 UTC; 22ms ago
 Main PID: 7036 (node)
   CGroup: /system.slice/wazuh-dashboard.service
           └─7036 /usr/share/wazuh-dashboard/bin/../node/bin/node --no-warnings --max-http-header-size=65536 --unhandled-rejections=warn /usr/share/wazuh-dashboard/bin/../src/cli/dist -c /etc/wazuh-dashboard/opensearch_dashboards.yml

Dec 14 17:03:01 redhat-7 systemd[1]: Started wazuh-dashboard.
-----------------------------
testing service option force-reload
-----------------------------
Service wazuh-dashboard status
-----------------------------
● wazuh-dashboard.service - wazuh-dashboard
   Loaded: loaded (/etc/systemd/system/wazuh-dashboard.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2022-12-14 17:03:11 UTC; 21ms ago
 Main PID: 7081 (node)
   CGroup: /system.slice/wazuh-dashboard.service
           └─7081 /usr/share/wazuh-dashboard/bin/../node/bin/node --no-warnings --max-http-header-size=65536 --unhandled-rejections=warn /usr/share/wazuh-dashboard/bin/../src/cli/dist -c /etc/wazuh-dashboard/opensearch_dashboards.yml

Dec 14 17:03:11 redhat-7 systemd[1]: Started wazuh-dashboard.
-----------------------------
testing service option stop
-----------------------------
Service wazuh-dashboard status
-----------------------------
● wazuh-dashboard.service - wazuh-dashboard
   Loaded: loaded (/etc/systemd/system/wazuh-dashboard.service; enabled; vendor preset: disabled)
   Active: inactive (dead) since Wed 2022-12-14 17:03:21 UTC; 24ms ago
  Process: 7081 ExecStart=/usr/share/wazuh-dashboard/bin/opensearch-dashboards -c /etc/wazuh-dashboard/opensearch_dashboards.yml (code=exited, status=0/SUCCESS)
 Main PID: 7081 (code=exited, status=0/SUCCESS)

Dec 14 17:03:14 redhat-7 opensearch-dashboards[7081]: {"type":"log","@timestamp":"2022-12-14T17:03:14Z","tags":["warning","config","deprecation"],"pid":7081,"message":"\"opensearch.requestHeadersWhitelist\" is deprecated and has been replaced by \"opensearch.request [...]

2022-12-14 20:30 UTC, rauldpm requested changes
Shouldn't these changes be made to the DEB packages as well?

Please add links to the package build and stack test pipelines.

2022-12-14 21:58 UTC, c-bordon commented
> 

 Builds packages:
 - indexer: https://ci.wazuh.info/view/Packages/job/Packages_builder/123707/console
 - dashboard:  https://ci.wazuh.info/view/Packages/job/Packages_builder/123708/console

Packages:
- indexer: https://packages-dev.wazuh.com/warehouse/test/4.4/rpm/wazuh-indexer-4.4.0-1975.x86_64.rpm
- dashboard: https://packages-dev.wazuh.com/warehouse/test/4.4/rpm/wazuh-dashboard-4.4.0-1975.x86_64.rpm
 
 Tests stack:
 - https://ci.wazuh.info/view/Tests/job/Test_stack/170/console

2022-12-15 09:04 UTC, okynos approved these changes

2022-12-15 09:32 UTC, DFolchA reviewed
What happens for systems that only have init.d?
What happens in docker containers?

2022-12-15 10:12 UTC, okynos commented
> What happens for systems that only have init.d? 
Wazuh dashboards is tested in recommended systems starting from CentOS 7 which comes with SystemD

>What happens in docker containers?
In container environment isn't recommended to use Service even SystemD. We will encourage users to use wazuh-docker approach

2022-12-15 10:13 UTC, DFolchA approved these changes

2022-12-15 10:40 UTC, merged