Fix Dashboard build so it can be installed in Rocky Linux 8 with FIPS enabled
wazuh/wazuh-packages pull request #1999
Opened 2022-12-19 17:38 UTC by verdx

|Related issue|
|---|
| #1934 |

## Description

This PR fixes the error given in Rocky Linux 8 when the package is built with `rpm 4.11`. 
- The machine on which it is built is changed to Rocky Linux 8.5
- The python shebangs are fixed using `pathfix.py` as `rpm 4.14` can't compile it with unclear shebangs.
- `_source_payload` and `_binary_payload` are added as variables on the RPM Specs so that the package can be installed in systems with `rpm 4.11`

## Logs example

All logs are in issue #1934 

## Tests

- [ ] Build with Jenkins
- Installation and upgrade:
  - [ ] CentOS 7
  - [ ] CentOS 8
  - [ ] Rocky Linux 8 with FIPS enabled
  - [ ] Amazon Linux 2
  - [ ] Red Hat Enterprise Linux 7
  - [ ] Red Hat Enterprise Linux 8
  - [ ] Red Hat Enterprise Linux 9
  - [ ] Ubuntu 16.04
  - [ ] Ubuntu 18.04
  - [ ] Ubuntu 20.04
  - [ ] Ubuntu 22.04

2022-12-20 09:25 UTC, DFolchA approved these changes

2022-12-20 09:25 UTC, DFolchA commented on stack/dashboard/rpm/build_package.sh
> +set -e
Why use set -e?

2022-12-20 09:26 UTC, DFolchA requested changes

2022-12-20 09:26 UTC, DFolchA commented on stack/dashboard/rpm/build_package.sh
> +set -e
Why use set -e?

2022-12-20 16:15 UTC, DFolchA approved these changes

2022-12-22 10:30 UTC, alberpilot approved these changes

2022-12-22 13:08 UTC, merged