Fix the errors in the dashboard for the AIO installation
wazuh/wazuh-packages pull request #2118
Opened 2023-03-07 15:57 UTC by verdx

|Related issue|
|---|
| #2111 |

## Description

This PR aims to fix the errors seen in the dashboard installation when an All-in-one installation is done in a system with less capabilities than the recommended ones. This errors have discovered some issues on the error treatment of the installation.

For now, function `passwords_getApiToken` now detects one more possible error and retries the Token downloading some number of times.

Test aio installation:
- [ ] Ubuntu 18
- [ ] Ubuntu 20
- [ ] Ubuntu 22
- [ ] CentOS 7
- [ ] CentOS 8
- [ ] Amazon Linux 2
- [ ] RHEL 7
- [ ] RHEL 8
- [ ] RHEL 9

2023-03-07 17:17 UTC, verdx commented
# Update
Doing the manual testing of the AIO installation, all systems finished the installation abruptly with the following error:
```
07/03/2023 17:07:32 DEBUG: Setting Wazuh indexer cluster passwords.
+ retries=0
+ max_internal_error_retries=10
++ curl -s -u '"wazuh":"wazuh"' -k -X POST '"https://localhost:55000/security/user/authenticate?raw=true"' --max-time 300 --retry 5 --retry-delay 5
+ TOKEN_API=
```

The problem is that the code was copied from version 4.4, where the request used to get the token is `POST`, but in version 4.3 it was still `GET`. The testing must be repeated after this change was added in commit https://github.com/wazuh/wazuh-packages/pull/2118/commits/bbf3031517e023cc3929f79faa5be1caeaf8db6e

#### GitHub Actions test
The github action test is failing on an unrelated thing to the changes done. For some reason yet undiscovered, it is looking for version `4.3.11` instead of `4.3.10`, and consequently not finding it. As per the urgency of the change, and seeing the error doesn't replicate locally, we are leaving for now the fixing of the github action for later.

2023-03-08 16:03 UTC, verdx commented
# Update 

A new problem has been encountered in the RHEL 9 AIO installation. The initialization of the dashboard fails on the curl correctly, with the error code inside variable `http_code` and enter the retry. The problem comes on the first curl of the retry, where it stops the script execution for some reason. As no rollback is done, the environment stays the same, and when trying exactly the same `curl`, it returns `200`, the expected output.

<details>
  <summary>RHEL 9 failed installation</summary>

```
[root@redhat9 vagrant]# bash wazuh-install.sh -a -i
08/03/2023 15:36:01 INFO: Starting Wazuh installation assistant. Wazuh version: 4.3.10
08/03/2023 15:36:01 INFO: Verbose logging redirected to /var/log/wazuh-install.log
08/03/2023 15:36:05 WARNING: Hardware and system checks ignored.
08/03/2023 15:36:10 INFO: Wazuh development repository added.
08/03/2023 15:36:10 INFO: --- Configuration files ---
08/03/2023 15:36:10 INFO: Generating configuration files.
08/03/2023 15:36:13 INFO: Created wazuh-install-files.tar. It contains the Wazuh cluster key, certificates, and passwords necessary for installation.
08/03/2023 15:36:13 INFO: --- Wazuh indexer ---
08/03/2023 15:36:13 INFO: Starting Wazuh indexer installation.
08/03/2023 15:38:29 INFO: Wazuh indexer installation finished.
08/03/2023 15:38:29 INFO: Wazuh indexer post-install configuration finished.
08/03/2023 15:38:29 INFO: Starting service wazuh-indexer.
08/03/2023 15:38:49 INFO: wazuh-indexer service started.
08/03/2023 15:38:49 INFO: Initializing Wazuh indexer cluster security settings.
08/03/2023 15:39:02 INFO: Wazuh indexer cluster initialized.
08/03/2023 15:39:02 INFO: --- Wazuh server ---
08/03/2023 15:39:02 INFO: Starting the Wazuh manager installation.
08/03/2023 15:40:40 INFO: Wazuh manager installation finished.
08/03/2023 15:40:40 INFO: Starting service wazuh-manager.
08/03/2023 15:40:57 INFO: wazuh-manager service started.
08/03/2023 15:40:57 INFO: Starting Filebeat installation.
08/03/2023 15:41:23 INFO: Filebeat installation finished.
08/03/2023 15:41:25 INFO: Filebeat post-install configuration finished.
08/03/2023 15:41:25 INFO: Starting service filebeat.
08/03/2023 15:41:25 INFO: filebeat service started.
08/03/2023 15:41:25 INFO: --- Wazuh dashboard ---
08/03/2023 15:41:25 INFO: Starting Wazuh dashboard installation.
08/03/2023 15:44:26 INFO: Wazuh dashboard installation finished.
08/03/2023 15:44:26 INFO: Wazuh dashboard post-install configuration finished.
08/03/2023 15:44:26 INFO: Starting service wazuh-dashboard.
08/03/2023 15:44:27 INFO: wazuh-dashboard service started.
+ retries=0
+ max_internal_error_retries=10
++ curl -s -u wazuh:wazuh -k -X GET 'https://localhost:55000/security/user/authenticate?raw=true' --max-time 300 --retry 5 --retry-delay 5
+ TOKEN_API=eyJhbGciOiJFUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YXp1aCIsImF1ZCI6IldhenVoIEFQSSBSRVNUIiwibmJmIjoxNjc4MjkwMjgwLCJleHAiOjE2NzgyOTExODAsInN1YiI6IndhenVoIiwicnVuX2FzIjpmYWxzZSwicmJhY19yb2xlcyI6WzFdLCJyYmFjX21vZGUiOiJ3aGl0ZSJ9.AJbUfUqkLfkpLAo1t9tc5aSzrFX1hwAqL55GIOcz4MFBZpeSzhP0R1YZqIiaDq2vxX7P1w68Ex7C9IUMgbI0tdm3AGMCgV-cjIpqVEtUufcOwiJhQCCfPGiv9FZx6d8Ce8Bjjr8A71l9H9-6zy5Tsv2705tQGhlNAILDNBJnVOxGMYYo
+ [[ eyJhbGciOiJFUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YXp1aCIsImF1ZCI6IldhenVoIEFQSSBSRVNUIiwibmJmIjoxNjc4MjkwMjgwLCJleHAiOjE2NzgyOTExODAsInN1YiI6IndhenVoIiwicnVuX2FzIjpmYWxzZSwicmJhY19yb2xlcyI6WzFdLCJyYmFjX21vZGUiOiJ3aGl0ZSJ9.AJbUfUqkLfkpLAo1t9tc5aSzrFX1hwAqL55GIOcz4MFBZpeSzhP0R1YZqIiaDq2vxX7P1w68Ex7C9IUMgbI0tdm3AGMCgV-cjIpqVEtUufcOwiJhQCCfPGiv9FZx6d8Ce8Bjjr8A71l9H9-6zy5Tsv2705tQGhlNAILDNBJnVOxGMYYo =~ Wazuh Internal Error ]]
+ [[ eyJhbGciOiJFUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YXp1aCIsImF1ZCI6IldhenVoIEFQSSBSRVNUIiwibmJmIjoxNjc4MjkwMjgwLCJleHAiOjE2NzgyOTExODAsInN1YiI6IndhenVoIiwicnVuX2FzIjpmYWxzZSwicmJhY19yb2xlcyI6WzFdLCJyYmFjX21vZGUiOiJ3aGl0ZSJ9.AJbUfUqkLfkpLAo1t9tc5aSzrFX1hwAqL55GIOcz4MFBZpeSzhP0R1YZqIiaDq2vxX7P1w68Ex7C9IUMgbI0tdm3AGMCgV-cjIpqVEtUufcOwiJhQCCfPGiv9FZx6d8Ce8Bjjr8A71l9H9-6zy5Tsv2705tQGhlNAILDNBJnVOxGMYYo =~ Wazuh Internal Error ]]
+ [[ eyJhbGciOiJFUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YXp1aCIsImF1ZCI6IldhenVoIEFQSSBSRVNUIiwibmJmIjoxNjc4MjkwMjgwLCJleHAiOjE2NzgyOTExODAsInN1YiI6IndhenVoIiwicnVuX2FzIjpmYWxzZSwicmJhY19yb2xlcyI6WzFdLCJyYmFjX21vZGUiOiJ3aGl0ZSJ9.AJbUfUqkLfkpLAo1t9tc5aSzrFX1hwAqL55GIOcz4MFBZpeSzhP0R1YZqIiaDq2vxX7P1w68Ex7C9IUMgbI0tdm3AGMCgV-cjIpqVEtUufcOwiJhQCCfPGiv9FZx6d8Ce8Bjjr8A71l9H9-6zy5Tsv2705tQGhlNAILDNBJnVOxGMYYo =~ Invalid credentials ]]
+ set +ex
+ retries=0
+ max_internal_error_retries=10
++ curl -s -u 'wazuh:d6qBBq2*doQonMhs+GMsup7ABp?5N6M0' -k -X GET 'https://localhost:55000/security/user/authenticate?raw=true' --max-time 300 --retry 5 --retry-delay 5
+ TOKEN_API=eyJhbGciOiJFUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YXp1aCIsImF1ZCI6IldhenVoIEFQSSBSRVNUIiwibmJmIjoxNjc4MjkwMzQ1LCJleHAiOjE2NzgyOTEyNDUsInN1YiI6IndhenVoIiwicnVuX2FzIjpmYWxzZSwicmJhY19yb2xlcyI6WzFdLCJyYmFjX21vZGUiOiJ3aGl0ZSJ9.AQqhKYvttfvYN0emeYk4DHnQldcSsFpTugL7djWC048TQi6XflPUZFkhhSzjxpWa9lfVNNLUtWZEKfw56DcdvjSyAAR0XAWODdP5diAVpTvUIRNqHqOqCTaznMFlmzGoVynQdmKJqaZ2JvUno8KCtcT4W0HCoHkFNTBZ5tMdkHWyibBb
+ [[ eyJhbGciOiJFUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YXp1aCIsImF1ZCI6IldhenVoIEFQSSBSRVNUIiwibmJmIjoxNjc4MjkwMzQ1LCJleHAiOjE2NzgyOTEyNDUsInN1YiI6IndhenVoIiwicnVuX2FzIjpmYWxzZSwicmJhY19yb2xlcyI6WzFdLCJyYmFjX21vZGUiOiJ3aGl0ZSJ9.AQqhKYvttfvYN0emeYk4DHnQldcSsFpTugL7djWC048TQi6XflPUZFkhhSzjxpWa9lfVNNLUtWZEKfw56DcdvjSyAAR0XAWODdP5diAVpTvUIRNqHqOqCTaznMFlmzGoVynQdmKJqaZ2JvUno8KCtcT4W0HCoHkFNTBZ5tMdkHWyibBb =~ Wazuh Internal Error ]]
+ [[ eyJhbGciOiJFUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YXp1aCIsImF1ZCI6IldhenVoIEFQSSBSRVNUIiwibmJmIjoxNjc4MjkwMzQ1LCJleHAiOjE2NzgyOTEyNDUsInN1YiI6IndhenVoIiwicnVuX2FzIjpmYWxzZSwicmJhY19yb2xlcyI6WzFdLCJyYmFjX21vZGUiOiJ3aGl0ZSJ9.AQqhKYvttfvYN0emeYk4DHnQldcSsFpTugL7djWC048TQi6XflPUZFkhhSzjxpWa9lfVNNLUtWZEKfw56DcdvjSyAAR0XAWODdP5diAVpTvUIRNqHqOqCTaznMFlmzGoVynQdmKJqaZ2JvUno8KCtcT4W0HCoHkFNTBZ5tMdkHWyibBb =~ Wazuh Internal Error ]]
+ [[ eyJhbGciOiJFUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YXp1aCIsImF1ZCI6IldhenVoIEFQSSBSRVNUIiwibmJmIjoxNjc4MjkwMzQ1LCJleHAiOjE2NzgyOTEyNDUsInN1YiI6IndhenVoIiwicnVuX2FzIjpmYWxzZSwicmJhY19yb2xlcyI6WzFdLCJyYmFjX21vZGUiOiJ3aGl0ZSJ9.AQqhKYvttfvYN0emeYk4DHnQldcSsFpTugL7djWC048TQi6XflPUZFkhhSzjxpWa9lfVNNLUtWZEKfw56DcdvjSyAAR0XAWODdP5diAVpTvUIRNqHqOqCTaznMFlmzGoVynQdmKJqaZ2JvUno8KCtcT4W0HCoHkFNTBZ5tMdkHWyibBb =~ Invalid credentials ]]
+ set +ex
+ common_logger 'Initializing Wazuh dashboard web application.'
++ date '+%d/%m/%Y %H:%M:%S'
+ now='08/03/2023 15:45:51'
+ mtype=INFO:
+ debugLogger=
+ nolog=
+ '[' -n 'Initializing Wazuh dashboard web application.' ']'
+ '[' -n 'Initializing Wazuh dashboard web application.' ']'
+ case ${1} in
+ message='Initializing Wazuh dashboard web application.'
+ shift 1
+ '[' -n '' ']'
+ '[' -z '' ']'
+ '[' 0 -eq 0 ']'
+ '[' -z '' ']'
+ tee -a /var/log/wazuh-install.log
+ printf '%s\n' '08/03/2023 15:45:51 INFO: Initializing Wazuh dashboard web application.'
08/03/2023 15:45:51 INFO: Initializing Wazuh dashboard web application.
+ installCommon_getPass admin
+ for i in "${!users[@]}"
+ '[' admin == admin ']'
+ u_pass='D0.ATaIaN42I2Wc.L6cmvgRkv2S2*zik'
+ for i in "${!users[@]}"
+ '[' kibanaserver == admin ']'
+ for i in "${!users[@]}"
+ '[' kibanaro == admin ']'
+ for i in "${!users[@]}"
+ '[' logstash == admin ']'
+ for i in "${!users[@]}"
+ '[' readall == admin ']'
+ for i in "${!users[@]}"
+ '[' snapshotrestore == admin ']'
++ curl -XGET https://localhost/status '-uadmin:D0.ATaIaN42I2Wc.L6cmvgRkv2S2*zik' -k -w '%{http_code}' -s -o /dev/null
+ http_code=503
+ retries=0
+ max_dashboard_initialize_retries=5
+ '[' 503 -ne 200 ']'
+ '[' 0 -lt 5 ']'
+ common_logger 'Wazuh dashboard web application not yet initialized. Waiting...'
++ date '+%d/%m/%Y %H:%M:%S'
+ now='08/03/2023 15:45:51'
+ mtype=INFO:
+ debugLogger=
+ nolog=
+ '[' -n 'Wazuh dashboard web application not yet initialized. Waiting...' ']'
+ '[' -n 'Wazuh dashboard web application not yet initialized. Waiting [...]

2023-03-08 17:21 UTC, rauldpm requested changes
Nice, minor changes

2023-03-09 09:28 UTC, davidcr01 approved these changes

2023-03-09 12:56 UTC, verdx commented
# Update
The number of retries and the time between retries for both the downloading of the token and the initialization of the dashboard have been increased after a test done for the 4.4 version of this PRs has proven more time was needed. The test is specifically the Amazon Linux 2 test done with less than recommended hardware, which traces are in this [commentary](https://github.com/wazuh/wazuh-packages/pull/2117#issue-1613349058)

2023-03-09 16:16 UTC, DFolchA approved these changes

2023-03-10 14:46 UTC, snaow approved these changes

2023-03-10 14:46 UTC, merged