Merge 4.5 master
wazuh/wazuh-packages pull request #2123
Opened 2023-03-09 14:15 UTC by DFolchA

|Related issue|
|---|
||

## Description

This PR megges the latest changes in 4.5 into master.

2023-03-09 14:31 UTC, verdx requested changes
LGTM, small change needed

2023-03-09 14:44 UTC, rauldpm approved these changes
LGTM

2023-03-09 14:57 UTC, jnasselle commented on unattended_installer/builder.sh
> +readonly source_branch="4.5"
+1

2023-03-13 14:09 UTC, DFolchA commented on unattended_installer/builder.sh
> +readonly source_branch="4.5"
Done https://github.com/wazuh/wazuh-packages/pull/2123/commits/11a2a3e8ecc7d6251520568f1c330ad988a55b70

2023-03-13 16:15 UTC, rauldpm submitted a review, later dismissed

2023-03-14 16:29 UTC, verdx approved these changes
LGTM

2023-03-30 20:45 UTC, jnasselle approved these changes
I've checked this PR in Jenkins and work as expected https://ci.wazuh.info/job/Packages_builder_tier/2906
LGTM!

2023-04-04 14:49 UTC, rauldpm reviewed
solaris/solaris10/pkginfo:VERSION="4.4.0"

2023-04-04 14:53 UTC, rauldpm requested changes
Review version references to older versions:

`solaris/solaris10/pkginfo:VERSION="4.4.0"`

2023-04-04 14:55 UTC, rauldpm approved these changes
LGTM

2023-04-04 14:58 UTC, jnasselle commented
WIP
Checking this PR in Jenkins https://ci.wazuh.info/job/Packages_builder_tier/2914/
https://ci.wazuh.info/job/PR_wazuh/16694/

2023-04-05 14:39 UTC, c-bordon approved these changes
LGTM

2023-04-11 20:51 UTC, rauldpm approved these changes
LGTM

2023-04-12 13:25 UTC, merged