Add Darwin 22 SCA files to specs
wazuh/wazuh-packages pull request #2148
Opened 2023-03-31 10:05 UTC by DFolchA

|Related issue|
|---|
|Closes #2137 |

## Description

This PR adds the necessary changes to include the new Darwin 22 SCA files to de SPECS.

## Logs example

## Tests

- Build the package in any supported platform
  - [ ] Linux
  - [ ] Windows
  - [ ] macOS
  - [ ] Solaris
  - [ ] AIX
  - [ ] HP-UX
- [ ] Package installation
- [ ] Package upgrade
- [ ] Package downgrade
- [ ] Package remove
- [ ] Package install/remove/install
- [ ] Change added to CHANGELOG.md

- Tests for Linux RPM
  - [ ] Build the package for x86_64
  - [ ] Build the package for i386
  - [ ] Build the package for armhf
  - [ ] Build the package for aarch64
  - [ ] `%files` section is correctly updated if necessary
- Tests for Linux deb
  - [ ] Build the package for x86_64
  - [ ] Build the package for i386
  - [ ] Build the package for armhf
  - [ ] Build the package for aarch64
  - [ ] Package install/remove/install
  - [ ] Package install/purge/install
  - [ ] Check file permissions after installing the package
- Tests for macOS
  - [ ] Test the package from macOS Sierra to Mojave
- Tests for Solaris
  - [ ] Test the package on Solaris 10
  - [ ] Test the package on Solaris 11
  - [ ] Check file permissions on Solaris 11 template
- Tests for IBM AIX
  - [ ] `%files` section is correctly updated if necessary
  - [ ] Check the changes from IBM AIX 5 to 7

2023-03-31 10:08 UTC, verdx approved these changes

2023-03-31 10:13 UTC, 72nomada approved these changes

2023-03-31 11:23 UTC, jnasselle requested changes

2023-03-31 11:23 UTC, jnasselle commented on macos/package_files/build.sh
> +    cp ${SOURCES_PATH}/etc/templates/config/darwin/21/sca.files ${INSTALLATION_SCRIPTS_DIR}/sca/darwin/22/
```suggestion
    cp ${SOURCES_PATH}/etc/templates/config/darwin/22/sca.files ${INSTALLATION_SCRIPTS_DIR}/sca/darwin/22/
```

2023-03-31 11:23 UTC, jnasselle commented on debs/SPECS/wazuh-manager/debian/rules
> +	cp etc/templates/config/darwin/21/sca.files ${TARGET_DIR}$(INSTALLATION_SCRIPTS_DIR)/sca/darwin/22
```suggestion
	cp etc/templates/config/darwin/22/sca.files ${TARGET_DIR}$(INSTALLATION_SCRIPTS_DIR)/sca/darwin/22
```

2023-03-31 11:23 UTC, jnasselle commented on debs/SPECS/wazuh-manager/debian/rules
> +	cp etc/templates/config/darwin/21/sca.files ${TARGET_DIR}$(INSTALLATION_SCRIPTS_DIR)/sca/darwin/22
https://github.com/wazuh/wazuh/blob/macOS-Ventura-SCA/etc/templates/config/darwin/22/sca.files

2023-03-31 11:23 UTC, jnasselle commented on macos/package_files/build.sh
> +    cp ${SOURCES_PATH}/etc/templates/config/darwin/21/sca.files ${INSTALLATION_SCRIPTS_DIR}/sca/darwin/22/
https://github.com/wazuh/wazuh/blob/macOS-Ventura-SCA/etc/templates/config/darwin/22/sca.files

2023-04-18 10:22 UTC, davidcr01 approved these changes

2023-04-18 10:23 UTC, verdx approved these changes

2023-04-18 20:49 UTC, rauldpm approved these changes

2023-04-19 11:26 UTC, c-bordon commented
## Tested in Jenkins:
Builds: https://ci.wazuh.info/view/Packages/job/Packages_builder_tier/2926
Upgrade tests: https://ci.wazuh.info/view/Tests/job/Test_upgrade_tier/2060

2023-04-19 11:30 UTC, jnasselle approved these changes

2023-04-27 10:31 UTC, merged