Include SCA policy for Alma Linux 8 in SPECS
wazuh/wazuh-packages pull request #2302
Opened 2023-07-20 07:21 UTC by vikman90

|Related issue|
|---|
|Closes #2283 |

## Description

This PR adds the necessary modifications to the SPECS to include the new Alma Linux 8 SCA policy.

## Logs example

## Tests

- Build the package in any supported platform
  - [x] Linux
  - [ ] Windows
  - [ ] macOS
  - [ ] Solaris
  - [ ] AIX
  - [ ] HP-UX
- [x] Package installation
- [x] Package upgrade
- [x] Package downgrade
- [x] Package remove
- [x] Package install/remove/install
- [ ] Change added to CHANGELOG.md

- Tests for Linux RPM
  - [x] Build the package for x86_64
  - [ ] Build the package for i386
  - [ ] Build the package for armhf
  - [ ] Build the package for aarch64
  - [ ] `%files` section is correctly updated if necessary
- Tests for Linux deb
  - [x] Build the package for x86_64
  - [ ] Build the package for i386
  - [ ] Build the package for armhf
  - [ ] Build the package for aarch64
  - [ ] Package install/remove/install
  - [ ] Package install/purge/install
  - [ ] Check file permissions after installing the package
- Tests for macOS
  - [ ] Test the package from macOS Sierra to Mojave
- Tests for Solaris
  - [ ] Test the package on Solaris 10
  - [ ] Test the package on Solaris 11
  - [ ] Check file permissions on Solaris 11 template
- Tests for IBM AIX
  - [ ] `%files` section is correctly updated if necessary
  - [ ] Check the changes from IBM AIX 5 to 7

2024-01-08 09:03 UTC, mjcr99 commented
## Issue updates
**(08/01/2024)** - Updated PR with the requested changes to add Almalinux 8 SCA files. The PR has been tested, the resulting packages contain the new files as expected:

<details><summary>Manager</summary>

**Manager package build:** https://ci.wazuh.info/job/Packages_builder/179409/

**Package installation:**
```
[root@almalinux8 vagrant]# yum install https://packages-dev.wazuh.com/warehouse/test/4.8/rpm/var/wazuh-manager-4.8.1-1.x86_64.rpm -y 
Failed to set locale, defaulting to C.UTF-8
AlmaLinux 8 - BaseOS                            3.1 MB/s | 4.0 MB     00:01    
AlmaLinux 8 - AppStream                         8.8 MB/s |  11 MB     00:01    
AlmaLinux 8 - Extras                             40 kB/s |  20 kB     00:00    
wazuh-manager-4.8.1-1.x86_64.rpm                 19 MB/s | 187 MB     00:09    
Dependencies resolved.
================================================================================
 Package              Architecture  Version           Repository           Size
================================================================================
Installing:
 wazuh-manager        x86_64        4.8.1-1           @commandline        187 M

Transaction Summary
================================================================================
Install  1 Package

Total size: 187 M
Installed size: 672 M
Downloading Packages:
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                        1/1 
  Running scriptlet: wazuh-manager-4.8.1-1.x86_64                           1/1 
  Installing       : wazuh-manager-4.8.1-1.x86_64                           1/1 
  Running scriptlet: wazuh-manager-4.8.1-1.x86_64                           1/1 
  Verifying        : wazuh-manager-4.8.1-1.x86_64                           1/1 

Installed:
  wazuh-manager-4.8.1-1.x86_64                                                  

Complete!
```

**SCA file found:**
```
[root@almalinux8 vagrant]# ls /var/ossec/ruleset/sca
cis_alma_linux_8.yml                  cis_rhel5_linux.yml.disabled
cis_amazon_linux_1.yml.disabled       cis_rhel6_linux.yml.disabled
cis_amazon_linux_2.yml.disabled       cis_rhel7_linux.yml.disabled
cis_amazon_linux_2023.yml.disabled    cis_rhel8_linux.yml.disabled
cis_apache_24.yml.disabled            cis_rhel9_linux.yml.disabled
cis_apple_macOS_10.11.yml.disabled    cis_rocky_linux_8.yml.disabled
cis_apple_macOS_10.12.yml.disabled    cis_sles11_linux.yml.disabled
cis_apple_macOS_10.13.yml.disabled    cis_sles12_linux.yml.disabled
cis_apple_macOS_10.14.yml.disabled    cis_sles15_linux.yml.disabled
cis_apple_macOS_10.15.yml.disabled    cis_solaris11.4.yml.disabled
cis_apple_macOS_11.1.yml.disabled     cis_solaris11.yml.disabled
cis_apple_macOS_12.0.yml.disabled     cis_sqlserver_2012.yml.disabled
cis_apple_macOS_13.x.yml.disabled     cis_sqlserver_2014.yml.disabled
cis_apple_macOS_14.0.yml.disabled     cis_sqlserver_2016.yml.disabled
cis_centos6_linux.yml.disabled        cis_sqlserver_2017.yml.disabled
cis_centos7_linux.yml.disabled        cis_sqlserver_2019.yml.disabled
cis_centos8_linux.yml.disabled        cis_ubuntu14-04.yml.disabled
cis_debian10.yml.disabled             cis_ubuntu16-04.yml.disabled
cis_debian11.yml.disabled             cis_ubuntu18-04.yml.disabled
cis_debian12.yml.disabled             cis_ubuntu20-04.yml.disabled
cis_debian7.yml.disabled              cis_ubuntu22-04.yml.disabled
cis_debian8.yml.disabled              cis_win10_enterprise.yml.disabled
cis_debian9.yml.disabled              cis_win11_enterprise.yml.disabled
cis_iis_10.yml.disabled               cis_win2012r2.yml.disabled
cis_mongodb_36.yml.disabled           cis_win2016.yml.disabled
cis_mysql5-6_community.yml.disabled   cis_win2019.yml.disabled
cis_mysql5-6_enterprise.yml.disabled  cis_win2022.yml.disabled
cis_nginx_1.yml.disabled              sca_unix_audit.yml.disabled
cis_oracle_database_19c.yml.disabled  web_vulnerabilities.yml.disabled
cis_postgre-sql-13.yml.disabled
```
</details>

<details><summary>Agent</summary>

**Agent package build:** https://ci.wazuh.info/job/Packages_builder/179410

**Package installation:**
```
[root@almalinux8 vagrant]# yum install https://packages-dev.wazuh.com/warehouse/test/4.8/rpm/var/wazuh-agent-4.8.1-1.x86_64.rpm -y
Failed to set locale, defaulting to C.UTF-8
AlmaLinux 8 - BaseOS                            2.5 MB/s | 4.0 MB     00:01    
AlmaLinux 8 - AppStream                         8.9 MB/s |  11 MB     00:01    
AlmaLinux 8 - Extras                             35 kB/s |  20 kB     00:00    
wazuh-agent-4.8.1-1.x86_64.rpm                  4.1 MB/s | 9.3 MB     00:02    
Dependencies resolved.
================================================================================
 Package             Architecture   Version          Repository            Size
================================================================================
Installing:
 wazuh-agent         x86_64         4.8.1-1          @commandline         9.3 M

Transaction Summary
================================================================================
Install  1 Package

Total size: 9.3 M
Installed size: 28 M
Downloading Packages:
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                        1/1 
  Running scriptlet: wazuh-agent-4.8.1-1.x86_64                             1/1 
  Installing       : wazuh-agent-4.8.1-1.x86_64                             1/1 
  Running scriptlet: wazuh-agent-4.8.1-1.x86_64                             1/1 
  Verifying        : wazuh-agent-4.8.1-1.x86_64                             1/1 

Installed:
  wazuh-agent-4.8.1-1.x86_64                                                    

Complete!
```

**SCA file found:**
```
[root@almalinux8 vagrant]# ls /var/ossec/ruleset/sca
cis_alma_linux_8.yml
```
</details>

2024-01-08 15:01 UTC, lchico requested changes
Great Job, @mjcr99. 
I have left some comments. Please take a look.

2024-01-08 15:10 UTC, lchico commented on rpms/SPECS/wazuh-manager.spec
> +  # We create this fix for the operating system that deprecated SySV. For now, this fix is for suse/openSUSE
But either way, I will suggest applying this in another PR.

2024-01-09 15:13 UTC, mjcr99 commented on rpms/SPECS/wazuh-agent.spec
> +cp etc/templates/config/almalinux/8/sca.files ${RPM_BUILD_ROOT}%{_localstatedir}/tmp/sca-%{version}-%{release}-tmp/almalinux/8
Fixed with https://github.com/wazuh/wazuh-packages/pull/2302/commits/f4df63df02bb9b25e0e632fe1c8b6551ea4b0514

2024-01-09 15:13 UTC, mjcr99 commented on rpms/SPECS/wazuh-manager.spec
> +  # We create this fix for the operating system that deprecated SySV. For now, this fix is for suse/openSUSE
Fixed with https://github.com/wazuh/wazuh-packages/commit/f4df63df02bb9b25e0e632fe1c8b6551ea4b0514Fixed with https://github.com/wazuh/wazuh-packages/pull/2302/commits/f4df63df02bb9b25e0e632fe1c8b6551ea4b0514

2024-01-09 15:14 UTC, mjcr99 commented on rpms/SPECS/wazuh-manager.spec
> +  if [ "${NAME}" = "Red Hat Enterprise Linux" ] && [ "$((${VERSION_ID:0:1}))" -ge 9 ]; then
Fixed with https://github.com/wazuh/wazuh-packages/pull/2302/commits/f4df63df02bb9b25e0e632fe1c8b6551ea4b0514

2024-01-09 17:18 UTC, ncvicchi approved these changes

2024-01-09 17:18 UTC, ncvicchi commented
LGTM!

2024-01-10 12:03 UTC, lchico approved these changes
Looks great. Thanks @mjcr99. LGTM!

2024-01-15 15:29 UTC, merged