Merge 4.5.4 into 4.6.0
wazuh/wazuh-packages pull request #2542
Opened 2023-10-20 16:51 UTC by TomasTurina

# Description

Merge 4.5.4 to the 4.6.0 branch.

2023-10-20 18:38 UTC, Dwordcito approved these changes

2023-10-20 19:13 UTC, jnasselle requested changes

2023-10-20 19:13 UTC, jnasselle commented on debs/SPECS/wazuh-agent/debian/changelog
> +wazuh-agent (4.5.4-RELEASE) stable; urgency=low
```suggestion
 -- Wazuh, Inc <info@wazuh.com> Tue, 31 Oct 2023 00:00:00 +0000
 
wazuh-agent (4.5.4-RELEASE) stable; urgency=low
```

2023-10-20 19:13 UTC, jnasselle commented on debs/SPECS/wazuh-manager/debian/changelog
> +wazuh-manager (4.5.4-RELEASE) stable; urgency=low
```suggestion
 -- Wazuh, Inc <info@wazuh.com> Tue, 31 Oct 2023 00:00:00 +0000
wazuh-manager (4.5.4-RELEASE) stable; urgency=low
```

2023-10-20 19:13 UTC, jnasselle commented on stack/indexer/deb/debian/changelog
> +wazuh-indexer (4.5.4-RELEASE) stable; urgency=low
```suggestion
 -- Wazuh, Inc <info@wazuh.com> Tue, 31 Oct 2023 00:00:00 +0000
wazuh-indexer (4.5.4-RELEASE) stable; urgency=low
```

2023-10-21 03:37 UTC, Dwordcito approved these changes

2023-10-21 03:38 UTC, merged