Firewall validation in the installation assistant
wazuh/wazuh-packages pull request #2555
Opened 2023-10-24 17:30 UTC by c-bordon

|Related issue|
|---|
|close https://github.com/wazuh/wazuh-packages/issues/2539|

## Description

Validations are created to detect if the system has Firewalld or UFW installed and enabled, to indicate by a Warning message which ports should be opened in the firewall

## Logs example

### Ubuntu Jammy: 
Firewalld: https://github.com/wazuh/wazuh-packages/issues/2539#issuecomment-1777142732
Without Firewalld: https://github.com/wazuh/wazuh-packages/issues/2539#issuecomment-1777131414
Firewalld and UFW: https://github.com/wazuh/wazuh-packages/issues/2539#issuecomment-1777448920

### Rocky Linux 8:
Firewalld: https://github.com/wazuh/wazuh-packages/issues/2539#issuecomment-1776009345
Without Firewalld: https://github.com/wazuh/wazuh-packages/issues/2539#issuecomment-1777122116
Firewalld and UFW: https://github.com/wazuh/wazuh-packages/issues/2539#issuecomment-1777449521

## Tests

Centos 7: https://ci.wazuh.info/view/Tests/job/Test_unattended/4553/console
Ubuntu Bionic: https://ci.wazuh.info/view/Tests/job/Test_unattended/4554/console
Distributed: https://ci.wazuh.info/view/Tests/job/Test_unattended_distributed/548/console

2023-10-24 18:03 UTC, teddytpc1 submitted a review, later dismissed

2023-10-25 08:09 UTC, davidcr01 commented on unattended_installer/install_functions/checks.sh
> +        f_message+="these ports: 1515 1514 ${http_port}"
```suggestion
        f_message+="these ports: 1515, 1514 ${http_port}"
```

2023-10-25 08:10 UTC, davidcr01 commented on unattended_installer/install_functions/checks.sh
> +        f_message+="these ports:${f_ports}"
```suggestion
    else
        f_message+="these ports:"
        for port in "${ports_list[@]}"; do
            f_message+=" ${port},"
        done

        # Deletes last comma
        f_message="${f_message%,}"
```

2023-10-25 08:12 UTC, davidcr01 requested changes
GJ! Please, consider changing the title of the PR and the suggested changes. Try to improve the message listing the ports with commas.

2023-10-25 11:58 UTC, teddytpc1 approved these changes

2023-10-25 13:19 UTC, davidcr01 approved these changes

2023-10-25 13:23 UTC, merged