Changed log message when not `yum` nor `apt-get` are found. Added clearer instructions on following steps.
wazuh/wazuh-packages pull request #2922
Opened 2024-04-19 10:45 UTC by CarlosALgit

|Related issue|
|---|
#2444
||

## Description

The previous log message was:
`ERROR: Couldn't find type of system`

This message has been changed to a more descriptive message:
`Couldn't find YUM or APT package manager. Try to install one of them with your current package manager. Then, launch the installation assistant again.`

2024-04-19 13:38 UTC, teddytpc1 requested changes

2024-04-19 13:38 UTC, teddytpc1 commented on unattended_installer/common_functions/common.sh
> +        common_logger -e "Couldn't find YUM or APT package manager. Try to install one of them with your current package manager. Then, launch the installation assistant again."
I would use the following message:
`Couldn't find YUM or APT package manager. Try installing the one corresponding to your operating system and then, launch the installation assistant again.`

2024-04-22 08:44 UTC, davidcr01 approved these changes

2024-04-23 19:00 UTC, teddytpc1 approved these changes

2024-04-24 19:07 UTC, teddytpc1 approved these changes

2024-04-24 19:07 UTC, merged