Adding some support for Arch Linux agent
wazuh/wazuh-packages pull request #594
Opened 2021-01-05 13:07 UTC by avielw

|Related issue|
#593

## Description
This commit should allow building Arch packages.

I've added a building script, Dockerfile and SPECS for the current version (4.2.0)

## Logs example

## Tests

- Build the package in any supported platform
  - [ ] Linux
  - [ ] Windows
  - [ ] macOS
  - [ ] Solaris
  - [ ] AIX
  - [ ] HP-UX
- [ ] Package installation
- [ ] Package upgrade
- [ ] Package downgrade
- [ ] Package remove
- [ ] Package install/remove/install
- [ ] Change added to CHANGELOG.md

- Tests for Linux RPM
  - [ ] Build the package for x86_64
  - [ ] Build the package for i386
  - [ ] Build the package for armhf
  - [ ] Build the package for aarch64
  - [ ] `%files` section is correctly updated if necessary
- Tests for Linux deb
  - [ ] Build the package for x86_64
  - [ ] Build the package for i386
  - [ ] Build the package for armhf
  - [ ] Build the package for aarch64
  - [ ] Package install/remove/install
  - [ ] Package install/purge/install
  - [ ] Check file permissions after installing the package
- Tests for macOS
  - [ ] Test the package from macOS Sierra to Mojave
- Tests for Solaris
  - [ ] Test the package on Solaris 10
  - [ ] Test the package on Solaris 11
  - [ ] Check file permissions on Solaris 11 template
- Tests for IBM AIX
  - [ ] `%files` section is correctly updated if necessary
  - [ ] Check the changes from IBM AIX 5 to 7

2021-09-09 14:56 UTC, okynos requested changes
Hello and thanks for your contribution, to merge this PR we need some points to be checked:
- Update last 4.2.0 and 4.2.1 changes.
- Test package building process.

I got an error after the PKGBUILD fixes
```
==> Entering fakeroot environment...
==> Starting package()...
==> ERROR: A failure occurred in package().
    Aborting...
```

We will be glad to help you with the process.

2021-09-09 14:56 UTC, okynos commented on arch/SPECS/4.2.0/wazuh-agent/arch/PKGBUILD
> +	cp etc/templates/config/ubuntu/16/04/sca.files ${pkgdir}/"PARAM_INSTALLATION_SCRIPTS_DIR"/sca/ubuntu/16/04
Remove unnecessary SCA files, let only generic ones.

2021-09-09 14:56 UTC, okynos commented on arch/SPECS/4.2.0/wazuh-agent/arch/PKGBUILD
> +	install -m 0644 src/systemd/wazuh-agent.service ${pkgdir}/usr/lib/systemd/system/
The path in 4.2.0 of this file is `src/init/templates/wazuh-agent.template`

2021-09-09 14:56 UTC, okynos commented on arch/SPECS/4.2.0/wazuh-agent/arch/PKGBUILD
> +	cp -p src/LOCATION ${pkgdir}/"PARAM_INSTALLATION_SCRIPTS_DIR"/src/
Removed on 4.2.0

2021-09-10 12:45 UTC, avielw commented
@okynos I think I did all the changes you asked for and fixed the issue with the package building. Now it looks like everything works for version 4.2.0.

2021-09-10 14:54 UTC, okynos approved these changes
LGTM.

2021-09-10 14:57 UTC, okynos commented
Thanks a lot for your contribution, we are always working to improve our product and our procedures.

Regards!

2021-09-10 14:57 UTC, merged

2021-09-10 19:10 UTC, avielw commented
Hey @okynos,
I saw that in branch **4.2** all the specs were updated to version 4.2.2, so I updated it for arch too. Do you want to pull this new commit too?

2021-09-13 07:18 UTC, okynos commented
Hello @avielw,

We will be glad if you open a new PR including such changes, thanks!

2021-09-16 11:49 UTC, avielw commented
@okynos In case you've misted it:
https://github.com/wazuh/wazuh-packages/pull/873