Removed  addElasticRepo function and Configure JVM options in installElasticsearch function
wazuh/wazuh-packages pull request #681
Opened 2021-03-24 11:52 UTC by jcruzlp

|Related issue|
|---|
|#627|

## Description
Closes #627 

Removed `addElasticRepo` function from `provision-opendistro.sh` library and the call from `provision.sh`

Also removed `Configure JVM options` in `installElasticsearch` from `provision-opendistro.sh` as those steps are not required on the Wazuh documentation installation guide.

## Logs example

After remove the listed code, I could run the script as follow: `sh provision.sh 4.1.2 1.12.0 7.10.0 dev 4.1.2 1 -d`

And got the following result:

```
Elasticsearch installation succeeded.
+ filebeat test output
elasticsearch: https://127.0.0.1:9200...
  parse url... OK
  connection...
    parse host... OK
    dns lookup... OK
    addresses: 127.0.0.1
    dial up... OK
  TLS...
    security: server's certificate chain verification is enabled
    handshake... OK
    TLS version: TLSv1.3
    dial up... OK
  talk to server... OK
  version: 7.10.0
+ '[' 0 '!=' 0 ']'
+ logger 'Filebeat installation succeeded.'
+ echo Filebeat installation succeeded.
Filebeat installation succeeded.
+ logger 'Initializing Kibana (this may take a while)'
+ echo Initializing Kibana '(this' may take a 'while)'
Initializing Kibana (this may take a while)
++ grep '200 OK'
++ curl -XGET https://localhost/status -I -uadmin:admin -k -s
+ [[ -n '' ]]
+ logger -ne '#'
+ echo -ne
+ sleep 10
++ curl -XGET https://localhost/status -I -uadmin:admin -k -s
++ grep '200 OK'
 ]][ -n HTTP/1.1 200 OK
+ logger '
Installation finished'
+ echo Installation finished
Installation finished
+ cleanInstall
+ rm -rf /etc/yum.repos.d/adoptopenjdk.repo
+ rm -rf /etc/yum.repos.d/wazuh.repo
+ yum clean all
Failed to set locale, defaulting to C
Loaded plugins: fastestmirror
Cleaning repos: base extras updates
Cleaning up list of fastest mirrors
Other repos take up 3.2 M of disk space (use --verbose for details)
+ rm -rf /vagrant
+ systemctl stop kibana filebeat elasticsearch
+ systemctl enable wazuh-manager
Created symlink from /etc/systemd/system/multi-user.target.wants/wazuh-manager.service to /usr/lib/systemd/system/wazuh-manager.service.

```

2021-03-24 13:41 UTC, okynos requested changes
LGTM but please include more testing.
Show that Wazuh and Elastic are well installed and working.
Also launch the Jenkins pipeline that build the OVA and test it.

2021-03-31 10:07 UTC, okynos approved these changes
LGTM.

2021-03-31 10:22 UTC, DFolchA approved these changes
LGTM

2021-04-06 07:19 UTC, Rebits approved these changes
LGTM

2021-04-07 08:10 UTC, alberpilot requested changes

2021-04-07 08:10 UTC, alberpilot commented on ova/Libraries/provision-opendistro.sh
> +        #Install Wazuh  Kibana plugin
```suggestion
        ## Install Wazuh  Kibana plugin
```

2021-04-12 15:48 UTC, alberpilot approved these changes

2021-04-12 15:48 UTC, merged