Fix 5.0 and 4.3 SPECS
wazuh/wazuh-packages pull request #696
Opened 2021-03-31 15:14 UTC by DFolchA

|Related issue|
|---|
||

## Description

This PR applies the changes done in #695 to versions 4.3 and 5.0

## Tests

- Build the package in any supported platform
  - [x] Linux
- [x] Package installation
- [x] Package upgrade
- [x] Package downgrade
- [x] Package remove
- [x] Package install/remove/install
- [x] Change added to CHANGELOG.md

- Tests for Linux RPM
  - [x] Build the package for x86_64
  - [x] Build the package for i386
  - [x] Build the package for armhf
  - [x] Build the package for aarch64
  - [x] `%files` section is correctly updated if necessary
- Tests for Linux deb
  - [x] Build the package for x86_64
  - [x] Build the package for i386
  - [x] Build the package for armhf
  - [x] Build the package for aarch64
  - [x] Package install/remove/install
  - [x] Package install/purge/install
  - [x] Check file permissions after installing the package

2021-03-31 15:31 UTC, okynos requested changes
Could you add the `4.1.1~4.1.4` changelogs? thanks.

2021-03-31 15:55 UTC, DFolchA commented on rpms/SPECS/4.2.0/wazuh-wui-4.2.0.spec
> +Summary:     Wazuh helps you to gain security visibility into your infrastructure by monitoring hosts at an operating system and application level. It provides the following capabilities: log analysi
Removed, and updated changelogs.

2021-04-06 14:53 UTC, alberpilot approved these changes

2021-04-06 15:09 UTC, okynos approved these changes
LGTM.

2021-04-06 15:20 UTC, merged