Fix broken symlink in RPM upgrade
wazuh/wazuh-packages pull request #830
Opened 2021-08-18 13:47 UTC by DFolchA

|Related issue|
|---|
|#828|

## Description
This PR fixes an error when upgrading from versions lower than 3.6.1

## Logs example

## Tests

- Build the package in any supported platform
  - [x] Linux
- [x] Package installation
- [x] Package upgrade
- [x] Package downgrade
- [x] Package remove
- [x] Package install/remove/install
- [ ] Change added to CHANGELOG.md

- Tests for Linux RPM
  - [x] Build the package for x86_64
  - [x] Build the package for i386
  - [x] Build the package for armhf
  - [x] Build the package for aarch64
  - [x] `%files` section is correctly updated if necessary

2021-08-18 14:36 UTC, okynos requested changes
Improve, thanks.

2021-08-18 14:36 UTC, okynos commented on rpms/SPECS/4.2.0/wazuh-agent-4.2.0.spec
> +  rm -rf %{_localstatedir}/etc/ossec-init.conf
Remove `-r` flag.

2021-08-18 14:36 UTC, okynos commented on rpms/SPECS/4.2.0/wazuh-manager-4.2.0.spec
> +  rm -rf %{_localstatedir}/etc/ossec-init.conf
Same here.

2021-08-19 07:50 UTC, DFolchA commented on rpms/SPECS/4.2.0/wazuh-manager-4.2.0.spec
> +  rm -rf %{_localstatedir}/etc/ossec-init.conf
Done in f0a4d40

2021-08-19 07:50 UTC, DFolchA commented on rpms/SPECS/4.2.0/wazuh-agent-4.2.0.spec
> +  rm -rf %{_localstatedir}/etc/ossec-init.conf
Done in f0a4d40

2021-08-19 07:54 UTC, okynos approved these changes
LGTM.

2021-08-19 07:54 UTC, merged